<?php echo $this->tag->javascriptInclude("themes/customize/js/ckeditor/ckeditor.js"); ?>
<?php echo $this->tag->stylesheetLink("themes/customize/css/bootstrapValidator/bootstrapValidator.min.css"); ?>
<div class="container containerBorder" id="container">
	<div class="col-md-12 bg-white">
		<div class="row">
			<br>
			<div class="col-md-12 bg-primary">
				<h1>Add an Item</h1>
				<p>Please note: This item will not appear in search results until it has been approved by our moderators.</p>
			</div>
		</div>
		<div class="row">
			<br>
			<div class="col-md-3 profile-widget">
				<?php $this->partial("layouts/elements/profile_widget") ?>
			</div>
			<?php echo Phalcon\Tag::form(array("thing/new", "method" => "post", "id" => "thingNew", "enctype"=>"multipart/form-data")); ?>
			<div class="col-md-6">
			<?php $this->flash->output(); ?>
			  	<div class="col-md-12">
					<div class="form-group">
						<label>Item Name</label>
						<input name="name" type="text" class="form-control" >
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Details</label>
						<textarea name="details" type="textarea" class="ckeditor form-control" ></textarea>
					</div>
				</div>
				<div class="col-md-12">
					<h3>Images</h3>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 1 (primary)</label>
							<input name="image[]" type="file" data-image="1" class="form-control file">
							<label>Caption</label>
							<textarea name="caption1" class="form-control" placeholder="--required--"></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<img src="http://placehold.it/100&text=image+1" id="imagePrev1" class="img-responsive img-thumbnail">
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action1">
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<button id="upload_more_photos_btn" type="button" class="btn btn-primary"><i class="fa fa-photo"></i> Upload more images</button>
				</div>
				<div id="upload_more_photos_div">
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 2</label>
							<input name="image[]"  type="file" data-image="2" class="form-control file">
							<label>Caption</label>
							<textarea name="caption2" class="form-control" placeholder="--required--"></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<img src="http://placehold.it/100&text=image+2" id="imagePrev2" class="img-responsive img-thumbnail">
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action2">
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 3</label>
							<input name="image[]"  type="file" data-image="3" class="form-control file">
							<label>Caption</label>
							<textarea name="caption3" class="form-control" placeholder="--required--"></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<img src="http://placehold.it/100&text=image+3" id="imagePrev3" class="img-responsive img-thumbnail">
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action3">
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 4</label>
							<input name="image[]"  type="file" data-image="4" class="form-control file">
							<label>Caption</label>
							<textarea name="caption4" class="form-control" placeholder="--required--"></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<img src="http://placehold.it/100&text=image+4" id="imagePrev4" class="img-responsive img-thumbnail">
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action4">
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 5</label>
							<input name="image[]"  type="file" data-image="5" class="form-control file">
							<label>Caption</label>
							<textarea name="caption5" class="form-control" placeholder="--required--"></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<img src="http://placehold.it/100&text=image+5" id="imagePrev5" class="img-responsive img-thumbnail">
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action5">
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 6</label>
							<input name="image[]"  type="file" data-image="6" class="form-control file">
							<label>Caption</label>
							<textarea name="caption6" class="form-control" placeholder="--required--"></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<img src="http://placehold.it/100&text=image+6" id="imagePrev6" class="img-responsive img-thumbnail">
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action6">
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 7</label>
							<input name="image[]"  type="file" data-image="7" class="form-control file">
							<label>Caption</label>
							<textarea name="caption7" class="form-control" placeholder="--required--"></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<img src="http://placehold.it/100&text=image+7" id="imagePrev7" class="img-responsive img-thumbnail">
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action7">
					</div>
				</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
					<div class="form-group">
					  <div class="col-lg-12 text-center">
						<button type="submit" class="btn btn-primary">Add Item</button>
					  </div>
					</div>
				
				<br>
			</div>
			<div class="col-md-3 containerBorder">
				<div class="col-md-12">
					<div class="form-group">
						<label>Price</label>
						<input name="price" type="text" class="form-control" >
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Condition</label>
						<select name="thing_condition_id"  type="select" class="form-control">
								<option value="">Select condition</option>
							<?php foreach ($thingConditions as $key => $thingCondition) { ?>
								<option value="<?php echo $thingCondition->id; ?>"><?php echo $thingCondition->name; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Category</label>
						<select name="thing_category_id"  type="select" class="form-control" id="thingCategory">
								<option value="">Select category</option>
							<?php foreach ($thingCategories as $key => $thingCategory) { ?>
								<option value="<?php echo $thingCategory->id; ?>" class="category category_<?php echo $thingCategory->id; ?>"><?php echo $thingCategory->name; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>
			</div>
			<?php echo Phalcon\Tag::endForm(); ?>
		</div>
		<br><br>
	</div>
</div>
<?php echo $this->tag->javascriptInclude("themes/customize/js/bootstrapValidator/bootstrapValidator.min.js"); ?>
<script type="text/javascript">
	$(document).ready(function() {
		
	

		function readURL(input, imgNo) {
		    if (input.files && input.files[0]) {
		        var reader = new FileReader();
		        reader.onload = function (e) {
		            $('#imagePrev'+imgNo).attr('src', e.target.result);
		            $('#action'+imgNo).html('<button class="btn btn-danger btn-xs trash" type="button" data-img="'+imgNo+'"><span class="fa fa-trash"></span></button>');
		        }
		        reader.readAsDataURL(input.files[0]);
		    }
		}

		$('[type="file"]').change(function(){
			var imgNo = $(this).data('image');
		    readURL(this, imgNo);
		});

		$(document).on('click', '.trash', function(){
			var imgNo = $(this).data('img');
			$('input[name="image'+imgNo+'"]').val('');
		    $('#imagePrev'+imgNo).attr('src', 'http://placehold.it/100&text=image+'+imgNo);
		    $('#action'+imgNo).html('');
		});
		// $('#realtyType').on('change', function(){ 
		// 	var categoryId = $(this).val();
		// 	$.getJSON("/mybarangay/realty_categories/list/"+categoryId, function(data) {
		// 	    $("#realtyCategory option").remove();
		// 	    $("#realtyCategory").append('<option value=""> Select sub-category</option>');
		// 	    $.each(data, function(){
		// 	        $("#realtyCategory").append('<option value="'+ this.id +'">'+ this.name +'</option>')
		// 	    });
		// 	});
		// });
		
		$('#upload_more_photos_div').hide();
		$('#upload_more_photos_btn').click(function() {
			$('#upload_more_photos_div').show(1000);
			$(this).hide();
		});
		
		$('#thingNew').bootstrapValidator({
            message: 'This value is not valid',
	        feedbackIcons: {
	            valid: 'glyphicon glyphicon-ok',
	            invalid: 'glyphicon glyphicon-remove',
	            validating: 'glyphicon glyphicon-refresh'
	        },
	        fields: {
	            name: {
	                validators: {
	                    notEmpty: {
	                        message: '* Required'
	                    }
	                }
	            },
	            details: {
	                validators: {
	                    notEmpty: {
	                        message: '* Required'
	                    }
	                }
	            },
	            price: {
	                validators: {
	                    notEmpty: {
	                        message: '* Required'
	                    },
			   numeric: {
	                        message: '* The price must be a number'
	                    }
	                }
	            },
	           thing_condition_id: {
	                validators: {
	                    notEmpty: {
	                        message: '* Required'
	                    }
	                }
	            },
		thing_category_id: {
	                validators: {
	                    notEmpty: {
	                        message: '* Required'
	                    }
	                }
	            }
            }
        });
	});
</script>

