
<style type="text/css">
	hr {
		background-color:#ddd;
		margin-top: 10px !important;
		margin-bottom: 10px !important;
	}
</style>
<?php echo $this->tag->javascriptInclude("themes/customize/js/ckeditor/ckeditor.js"); ?>
<div class="container containerBorder top_margin" id="container">
	<div class="col-md-12 bg-white">
		<div class="row">
			<div class="col-md-12 bg-primary container" style="margin-bottom:25px;">
				<h1>Edit a Thing</h1>
				<p>Please note: This property will not appear in search results until it has been approved by our moderators.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 ">
				<?php $this->partial("layouts/elements/profile_widget"); ?>	
			</div>
			<?php echo Phalcon\Tag::form(array("thing/update/".$thing->id, "method" => "post", "id" => "thingUpdate", "enctype"=>"multipart/form-data")); ?>
			<input name="id" type="hidden" class="form-control hidden" value="<?php echo $thing->id; ?>" >
			<div class="col-md-6">
			  	<div class="col-md-12">
					<div class="form-group">
						<label>Item Name</label>
						<input name="name" type="text" class="form-control" value="<?php echo $thing->name; ?>">
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Details</label>
						<textarea name="details" type="textarea" class="ckeditor form-control"><?php echo $thing->details; ?></textarea>
					</div>
				</div>
				<div class="col-md-12">
					<h3>Images</h3>
				</div>
				<?php
					$fileId = array(0 => '', 1 => '', 2 => '', 3 => '', 4 => '', 5 => '', 6 => '');
					$propertyImg = array(0 => 'http://placehold.it/100&text=image+1', 1 => 'http://placehold.it/100&text=image+2', 2 => 'http://placehold.it/100&text=image+3', 3 => 'http://placehold.it/100&text=image+4', 4 => 'http://placehold.it/100&text=image+5', 5 => 'http://placehold.it/100&text=image+6', 6 => 'http://placehold.it/100&text=image+7');					
					$caption = array(0 => '', 1 => '', 2 => '', 3 => '', 4 => '', 5 => '', 6 => '');
					foreach ($thingPhotos as $key => $thingPhoto) {
						$fileId[$key] = $thingPhoto->id;
						$propertyImg[$key] = $thingPhoto->file_path.$thingPhoto->filename;
						$caption[$key] = $thingPhoto->caption;
					}

				?>

				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 1 (primary)</label>
							<input name="fileId1" value="<?php echo $fileId[0]; ?>" type="text" class="form-control hidden">
							<input name="image1" data-image="1" type="file" class="form-control file">
							<label>Caption</label>
							<textarea name="caption1" class="form-control"><?php echo $caption[0]; ?></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<?php echo Phalcon\Tag::image(array($propertyImg[0], 'class' => 'img-responsive img-thumbnail', 'id' => 'imagePrev1')); ?>
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action1">
						<?php if($fileId[0]){ ?>
							<button class="btn btn-danger btn-xs trash" type="button" data-img="1"><span class="fa fa-trash"></span></button>
						<?php } ?>
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>

				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 2</label>
							<input name="fileId2" value="<?php echo $fileId[1]; ?>" type="text" class="form-control hidden">
							<input name="image2" data-image="2" type="file" class="form-control file">
							<label>Caption</label>
							<textarea name="caption2" class="form-control"><?php echo $caption[1]; ?></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<?php echo Phalcon\Tag::image(array($propertyImg[1], 'class' => 'img-responsive img-thumbnail', 'id' => 'imagePrev2')); ?>
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action2">
						<?php if($fileId[1]){ ?>
							<button class="btn btn-danger btn-xs trash" type="button" data-img="2"><span class="fa fa-trash"></span></button>
						<?php } ?>
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 3</label>
							<input name="fileId3" value="<?php echo $fileId[2]; ?>" type="text" class="form-control hidden">
							<input name="image3" data-image="3" type="file" class="form-control file">
							<label>Caption</label>
							<textarea name="caption3" class="form-control"><?php echo $caption[2]; ?></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<?php echo Phalcon\Tag::image(array($propertyImg[2], 'class' => 'img-responsive img-thumbnail', 'id' => 'imagePrev3')); ?>
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action3">
						<?php if($fileId[2]){ ?>
							<button class="btn btn-danger btn-xs trash" type="button" data-img="3"><span class="fa fa-trash"></span></button>
						<?php } ?>
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 4</label>
							<input name="fileId4" value="<?php echo $fileId[3]; ?>" type="text" class="form-control hidden">
							<input name="image4" data-image="4" type="file" class="form-control file">
							<label>Caption</label>
							<textarea name="caption4" class="form-control"><?php echo $caption[3]; ?></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<?php echo Phalcon\Tag::image(array($propertyImg[3], 'class' => 'img-responsive img-thumbnail', 'id' => 'imagePrev4')); ?>
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action4">
						<?php if($fileId[3]){ ?>
							<button class="btn btn-danger btn-xs trash" type="button" data-img="4"><span class="fa fa-trash"></span></button>
						<?php } ?>
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 5</label>
							<input name="fileId5" value="<?php echo $fileId[4]; ?>" type="text" class="form-control hidden">
							<input name="image5" data-image="5" type="file" class="form-control file">
							<label>Caption</label>
							<textarea name="caption5" class="form-control"><?php echo $caption[4]; ?></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<?php echo Phalcon\Tag::image(array($propertyImg[4], 'class' => 'img-responsive img-thumbnail', 'id' => 'imagePrev5')); ?>
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action5">
						<?php if($fileId[4]){ ?>
							<button class="btn btn-danger btn-xs trash" type="button" data-img="5"><span class="fa fa-trash"></span></button>
						<?php } ?>
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 6</label>
							<input name="fileId6" value="<?php echo $fileId[5]; ?>" type="text" class="form-control hidden">
							<input name="image6" data-image="6" type="file" class="form-control file">
							<label>Caption</label>
							<textarea name="caption6" class="form-control"><?php echo $caption[5]; ?></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<?php echo Phalcon\Tag::image(array($propertyImg[5], 'class' => 'img-responsive img-thumbnail', 'id' => 'imagePrev6')); ?>
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action6">
						<?php if($fileId[5]){ ?>
							<button class="btn btn-danger btn-xs trash" type="button" data-img="6"><span class="fa fa-trash"></span></button>
						<?php } ?>
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="col-md-12">
					<div class="col-md-6">
						<div class="form-group">
							<label>Image 7</label>
							<input name="fileId7" value="<?php echo $fileId[6]; ?>" type="text" class="form-control hidden">
							<input name="image7" data-image="7" type="file" class="form-control file">
							<label>Caption</label>
							<textarea name="caption7" class="form-control"><?php echo $caption[6]; ?></textarea>
						</div>
					</div>
					<div class="col-md-5">
						<?php echo Phalcon\Tag::image(array($propertyImg[6], 'class' => 'img-responsive img-thumbnail', 'id' => 'imagePrev7')); ?>
					</div>
					<div class="col-md-1 center-block" data-toggle="tooltip" title="remove" id="action7">
						<?php if($fileId[6]){ ?>
							<button class="btn btn-danger btn-xs trash" type="button" data-img="7"><span class="fa fa-trash"></span></button>
						<?php } ?>
					</div>
				</div>
				<div class="col-md-11">
					<hr>
				</div>
				<div class="form-group">
				  <div class="col-lg-12 text-center">
					<button type="submit" class="btn btn-primary">Update Item</button>
				  </div>
				</div>
				
				<br>
			</div>
			<div class="col-md-3 containerBorder">
				<div class="col-md-12">
					<div class="form-group">
						<label>Price</label>
						<input name="price" type="text" class="form-control" value="<?php echo number_format($thing->price, 2); ?>">
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Condition</label>
						<select name="thing_condition_id"  type="select" class="form-control">
								<option value="">Select condition</option>
							<?php foreach ($thingConditions as $key => $thingCondition) { ?>
								<?php if ($thingCondition->id == $thing->thing_condition_id) { ?>
									<option value="<?php echo $thingCondition->id; ?>" selected><?php echo $thingCondition->name; ?></option>
								<?php } else { ?>
									<option value="<?php echo $thingCondition->id; ?>" selected><?php echo $thingCondition->name; ?></option>
								<?php } ?>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Category</label>
						<select name="thing_category_id"  type="select" class="form-control" id="thingCategory">
								<option value="">Select category</option>
							<?php foreach ($thingCategories as $key => $thingCategory) { ?>
								<?php if($thingCategory->id == $thing->thing_category_id){ ?>
										<option value="<?php echo $thingCategory->id; ?>" class="category category_<?php echo $thingCategory->id; ?>" selected><?php echo $thingCategory->name; ?></option>
								<?php } else { ?>
										<option value="<?php echo $thingCategory->id; ?>" class="category category_<?php echo $thingCategory->id; ?>"><?php echo $thingCategory->name; ?></option>
								<?php } ?>
							<?php } ?>
						</select>
					</div>
				</div>
			</div>
			<?php echo Phalcon\Tag::endForm(); ?>
		</div>
		<br><br>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {

		$('#realtyType').on('change', function(){ 
			var categoryId = $(this).val();
			$.getJSON("/mybarangay/realty_category/list/"+categoryId, function(data) {
			    $("#realtyCategory option").remove();
			    $("#realtyCategory").append('<option value=""> Select category</option>');
			    $.each(data, function(){
			        $("#realtyCategory").append('<option value="'+ this.id +'">'+ this.name +'</option>')
			    });
			});
		});

		function readURL(input, imgNo) {
		    if (input.files && input.files[0]) {
		        var reader = new FileReader();
		        reader.onload = function (e) {
		            $('#imagePrev'+imgNo).attr('src', e.target.result);
		            $('#action'+imgNo).html('<button class="btn btn-danger btn-xs trash" type="button" data-img="'+imgNo+'"><span class="fa fa-trash"></span></button>');
		        }
		        reader.readAsDataURL(input.files[0]);
		    }
		}

		$('[type="file"]').change(function(){
			var imgNo = $(this).data('image');
		    readURL(this, imgNo);
		});

		$(document).on('click', '.trash', function(){
			var imgNo = $(this).data('img');
			$('input[name="image'+imgNo+'"]').val('');
		    $('#imagePrev'+imgNo).attr('src', 'http://placehold.it/100&text=image+'+imgNo);
		    $('#action'+imgNo).html('');
		});
		
	});
</script>


