<div class="container" id="container">
	<div class="col-md-12 containerBorder">
		<div class="row">
			<br>
			<div class="col-md-3">
				<?php $member = $thing->Members; ?>
				<?php if(isset($userSession['id'])) { $memberId = $userSession['id']; } else { $memberId = ''; } ?>
				<?php if($memberId == $member->id) { ?>
				<?php $this->partial("layouts/elements/profile_widget") ?>
				<?php } ?>
				<?php if($memberId != $member->id) { ?>
				<?php $this->partial("layouts/elements/member_widget") ?>
				<?php } ?>
				<div class="panel panel-default well">
					<div class="panel-body">
					<h3 class="text-danger"><strong>Another container</strong></h3>
					</div>
				</div>
			</div>
			<div class="col-md-9">
				<div class="col-md-12 bg-primary">
					<div class="col-md-9">
					<h2><?php echo $thing->name; ?></h2>
					<p><?php echo $thing->ThingCategories->name; ?></p>
					</div>
					<div class="col-md-3">
					<h2> &nbsp;</h2>
					<p data-toggle="tooltip" title="price" class="price label label-danger"><span class="fa fa-money"></span> <?php echo "P ". number_format($thing->price,2); ?></p>
					</div>
				</div>
				<div class="col-md-8">
					<br>
					<div class="row">
					<?php foreach($thing->thingphotos as $key => $thingPhoto){ ?>
						<?php if($key == 0){ ?>
							<div class="col-md-12" style="position:relative;">
							<?php echo Phalcon\Tag::image(array($thingPhoto->file_path.$thingPhoto->filename, 'class' => 'img-responsive img-rounded img-current')); ?>
								<div class="text-center center-block" style="position:absolute;width:95%;background-color:black;opacity:0.7;color:white;bottom:0;padding:10px;font-size:16px;z-index:5;" id="captionCurrent"><?php echo $thingPhoto->caption; ?></div>

							</div>
							
						<?php }  ?>
							<div class="col-md-2">
								<br>
								<a href="javascript:void(0);">
								<?php echo Phalcon\Tag::image(array($thingPhoto->file_path.$thingPhoto->filename, 'class' => 'img-responsive img-rounded img-item', 'data-caption' => $thingPhoto->caption)); ?>
								</a>
							</div>
					<?php } ?>
					</div>
					<?php if ($memberId == $thing->member_id) {?>
					<div class="pull-right">
					<?php echo Phalcon\Tag::linkTo(array('thing/update/'.$thing->id, '<span class="fa fa-pencil"></span>', 'data-toggle' => 'tooltip', 'title' => 'Edit', 'class' => 'text-danger')); ?>
					</div>
					<?php } ?>
				</div>

				<div class="col-md-4">
				<br>
					<div class="panel panel-default ">
						<div class="panel-body">
							<p class="title-heading text-primary"><strong><?php echo $thing->ThingConditions->name; ?></strong></p>
							<p><span class="fa fa-cube "></span> <?php echo $thing->ThingCategories->name; ?></p>
							<p><span class="fa fa-clock-o "></span> Date posted <?php echo date('m-d-Y h:i A', strtotime($thing->created)); ?></p>
							
						</div>
					</div>
					<div class="panel panel-default well">
						<div class="panel-body">
						<h3 class="text-danger"><strong>Related Items</strong></h3>
						</div>
					</div>
				</div>
			<div class="col-md-8">
				<br>
					<h2>Details</h2>
					<p class="text-justify"><?php echo $thing->details; ?></p>
					
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {

		$('.img-item').on('click', function(){
			var src = $(this).attr('src');
			var caption = $(this).data('caption');
			$('.img-current').attr('src', src);
			$('#captionCurrent').text(caption);
		});
		
	});
</script>
