<div class="container" id="container">
    <div class="col-md-12 bg-white">
        <div class="row">
            <br>
            <div class="col-md-12 bg-primary">
                <h1>Add an Event</h1>
                <p>Please note: This event's details will not appear in search results until it has been approved by our moderators.</p>
            </div>
        </div>
        <div class="row">
            <br>
            <div class="col-md-4">
                <form action="new_event" method="post" class="" id="newEventForm">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Event Name</label>
                            <input name="name" type="text" class="form-control" placeholder="Milo Fun Run">
                        </div>
                        <div class="form-group">
                            <label>Event Date</label>
                            <input name="eventdate" type="date" class="form-control" placeholder="2014-12-31" >
                        </div>
                        <div class="form-group">
                            <label>Event Website / Link</label>
                            <input name="website" type="text" class="form-control" placeholder="http://milo.com.ph">
                        </div>
                        <div class="form-group">
                            <label>Contact Number</label>
                            <input name="telephone" type="text" class="form-control" placeholder="(222) 222-2222">
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <input name="street" type="text" class="form-control" placeholder="123 anywhere street">
                        </div>
                        <div class="form-group">
                            <label>City</label>
                            <input name="city" type="text" class="form-control"  placeholder="City">
                        </div>

                        <div class="form-group">
                            <label>Country</label>
                            <select name="country_id"  type="select" class="form-control">
                                <option value="">Select country</option>
                                <?php foreach ($countries as $key => $country) { ?>
                                    <option value="<?php echo $country->id; ?>"><?php echo $country->country; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Event Category</label>
                            <select name="event_category_id"  type="select" class="form-control">
                                <option value="">Select category</option>
                                <?php foreach ($eventsCategories as $key => $eventsCategory) { ?>
                                    <option value="<?php echo $eventsCategory->id; ?>"><?php echo $eventsCategory->name; ?></option>
                                <?php } ?>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Event Details / Info</label>
                            <textarea rows="5" cols="40" name="eventinfo" class="form-control"  placeholder="Any detail you would want the world to know"></textarea>
                        </div>
                        <br />
                        <div class="form-group">
                            <span class="fa fa-star btn btn-success btn-xs rate" data-rate="1"></span>&nbsp;<span class="fa fa-star btn btn-success btn-xs rate" data-rate="2"></span>&nbsp;<span class="fa fa-star btn btn-danger btn-xs rate" data-rate="3"></span>&nbsp;<span class="fa fa-star btn btn-danger btn-xs rate" data-rate="4"></span>&nbsp;<span class="fa fa-star btn btn-warning btn-xs rate" data-rate="5"></span>
                            <input name="rate" type="text" class="hidden" id="rate">
                        </div>
                        <div class="form-group">
                            <label> Write a review for this event</label>
                            <textarea name="review" type="textarea" class="form-control" placeHolder="Start your review..."></textarea>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-12 text-center">
                                <button type="submit" class="btn btn-primary">Add Event</button>
                            </div>
                        </div>

                    </div>
                </form>
                <br>
            </div>
            <div class="col-md-8 text-center">
                <h1 class="text-danger"><strong>Pangyayari</strong></h1>
                <h3>Endorse your events in <span class="text-primary"><strong>MyBarangay</strong></span>.</h3>
                <div class="col-md-8 col-md-offset-3">
                    <?php echo Phalcon\Tag::image(array("themes/mybarangay1/img/biz/new_biz.jpg", 'class' => 'img-responsive img-rounded img-block')); ?>
                </div>
            </div>
        </div>
        <br><br>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.rate').on('click', function(){
            var rate = $(this).data('rate');
            $('#rate').val(rate);
        });
    });
</script>

