<section class="cd-section">
		
			<section class="cd-intro">
				<h1 class="cd-headline letters type">
					<span>My favourite food is</span> 
					<span class="cd-words-wrapper waiting">
						<b class="is-visible">adobo!</b>
						<b>lechon!</b>
						<b>halo-halo! :)</b>
					</span>
				</h1>
			</section> <!-- cd-intro -->
			<p>We invite you to help build OUR barangay. Come join our vision of a global Filipino community that shares, supports and empowers its members. Let's unite with each other and for each other. Let's put our resources together and grow as one. Let's support our very own talents, initiatives, businesses and professions. Big or small, let's help each other thrive through our barangay.  Let's show our children and the world, the resilience, the will, and the beauty of the Filipino. Together we can. </p>
			<div class="row">
				<div class="col-md-6 col-md-offset-3"><?php $this->flash->output(); ?></div>
			</div>
			<?php if( !isset($firstName) ) { ?>
			<div class="cd-modal-action">
				<a href="javascript:void(0);" class="btn" data-type="modal-trigger" id="modalSignup">Create a free account</a>
				<span class="cd-modal-bg"></span>
			</div>
			<?php  } ?>
			<?php if( isset($firstName) ) { ?>
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert">×</button>
						Mabuhay, <strong><?php echo $firstName; ?></strong>!
					</div>
				</div>
			</div>	
			<?php  } ?>
			<div class="cd-modal container">
				<div class="cd-modal-content">
					<div class="col-md-4 col-md-offset-1">
						<h4>Sign Up for MyBarangay</h4>
						<small>Come join our vision of a global Filipino community that shares, supports and empowers its members.</small><br><br>
						<div class="form-group">
						<?php echo $this->tag->linkTo(array('member/loginWithFacebook', '<i class="fa fa-facebook-official fa-lg"></i>  &nbsp;<span id="fbText">Sign up with FACEBOOK</span>', 'class' => 'btn btn-primary btn-block')) ?>
						</div>
						<div class="form-group">
							<span id="signinButton">
							  	<span
							    class="g-signin btn btn-danger btn-block"
							    data-callback="googleAuth"
							    data-redirecturi="postmessage"
							    data-clientid="155579594624-3c5g7n9sf7baegg498ol4a5j48v7gojf.apps.googleusercontent.com"
							    data-cookiepolicy="http://mybarangay.cloudapp.net"
							    data-scope="profile email">
							    	<i class="fa fa-google-plus-square fa-lg"></i>  &nbsp;<span id="GText">Sign up with GOOGLE</span>
							  	</span>
							</span>
						</div>
						<small>Don't worry, we never post without your permission.</small>
						<hr>
							<form action="member/signup" method="post" class="" id="signUpForm">
								  <fieldset>
									<div class="form-group">
										<input name="first_name" type="text" class="form-control" placeholder="First Name">
									</div>
									<div class="form-group">
										
										<input name="last_name" type="text" class="form-control" placeholder="Last Name">
									</div>
									<div class="form-group">
										<input name="email" type="email" class="form-control" id="inputEmail" placeholder="Email">
									</div>
									
									<div class="form-group">
										<input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password">
									</div>
									<div class="form-group">
										<input name="confirm_password" type="password" class="form-control" id="inputConfirmPassword" placeholder="Confirm Password">
									</div>
									<div class="checkbox">
									  <label>
										<input type="checkbox"> I agree to the terms
									  </label>
									</div>
					
									<div class="form-group">
									  <div class="col-lg-12 text-center">
										<button type="button" class="btn btn-info cancel">Cancel</button>
										<button type="submit" class="btn btn-primary">Submit</button>
									  </div>
									</div>
								  </fieldset>
								</form>

								<form action="member/login" method="post" class="hidden" id="loginForm">
								  <fieldset>
									<div class="form-group">
										<input name="email" type="email" class="form-control" id="inputEmail" placeholder="Email">
									</div>
									
									<div class="form-group">
										<input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password">
									</div>
									<div class="form-group">
										<div class="col-lg-12 text-center">
											<small><a href="javascript:void(0);" id="forgotPassword">Forgot password</a></small>
											<br><br>
										</div>
									</div>

									<div class="form-group">
									  <div class="col-lg-12 text-center">
										<button type="button" class="btn btn-info cancel">Cancel</button>
										<button type="submit" class="btn btn-primary">Submit</button>
									  </div>
									</div>

								  </fieldset>
								</form>

								<form action="member/forgotPassword" method="post" class="hidden" id="resetPasswordForm">
								  <fieldset>
									<div class="form-group">
										<input name="email" type="email" class="form-control" id="inputEmail" placeholder="Email">
									</div>					
									<div class="form-group">
									  <div class="col-lg-12 text-center">
										<button type="button" class="btn btn-info cancel">Cancel</button>
										<button type="submit" class="btn btn-primary">Submit</button>
									  </div>
									</div>
								  </fieldset>
								</form>
								<br>
					</div>
					<div class="col-md-6">
						<p><strong>MyBarangay</strong> is a virtual bridge that links Filipinos all over the world like never before.  It provides a venue for all of us to follow our hearts and come together to share, connect and feel at home. It is an invitation to assemble as one and build our global community. A community with no boundaries. A community of support, resources and solutions. A community with a positive voice that we can reach out to from anywhere in the world. A community that is truly ours:  <strong>MyBarangay.</strong> </p>
								
					</div>
				</div> <!-- cd-modal-content -->
			</div> <!-- cd-modal -->
			<a href="javascript:void(0);" class="cd-modal-close">Close</a>
		
		</section>
		
		<div class="container" id="container">
			<h3 class="example-title">Best of MyBarangay : Vancouver</h3>
			<div class="row">
				<div class="col-md-6">
					<div class="panel">
						<ul id="myTab1" class="nav nav-tabs nav-justified">
							<li class="active bg-success"><a href="#home1" data-toggle="tab">Restaurants</a></li>
							<li class="bg-success"><a href="#profile1" data-toggle="tab">Health & Medical</a></li>
							<li class="dropdown bg-success"><a href="#" id="myTabDrop1-1" class="dropdown-toggle" data-toggle="dropdown">Others <b class="caret"></b></a>
								<ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1">
									<li><a href="#dropdown1-1" tabindex="-1" data-toggle="tab">@Nightlife</a></li><li><a href="#dropdown1-2" tabindex="-1" data-toggle="tab">@Shopping</a></li>
								</ul>
							</li>
						</ul>
						<div id="myTabContent" class="tab-content">
							<div class="tab-pane fade active in" id="home1">
								<?php echo Phalcon\Tag::image(array("themes/mybarangay1/img/resto.png", "alt" => "Restaurants Photo")); ?>
								<!-- <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.</p> -->
							</div>
							<div class="tab-pane fade" id="profile1">
								<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee.</p>
							</div>
							<div class="tab-pane fade" id="dropdown1-1">
								<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone...</p>
							</div>
							<div class="tab-pane fade" id="dropdown1-2">
								<p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche ...</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="panel">
						<div class="tabbable tabs-below">
							<div id="myTabContent" class="tab-content">
								<div class="tab-pane fade active in" id="home2">
									<!-- <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.</p> -->
									<?php echo Phalcon\Tag::image(array("themes/mybarangay1/img/auto.png", "alt" => "Automobile Photo")); ?>
								</div>
								<div class="tab-pane fade" id="profile2">
									<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee.</p>
								</div>
								<div class="tab-pane fade" id="dropdown2-1">
									<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone...</p>
								</div>
								<div class="tab-pane fade" id="dropdown2-2">
									<p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche ...</p>
								</div>
							</div>
							<ul id="myTab2" class="nav nav-tabs nav-justified">
								<li class="active btn-warning"><a href="#home2" data-toggle="tab">SUVs</a></li>
								<li class="btn-warning"><a href="#profile2" data-toggle="tab">Sports Car</a></li>
								<li class="dropdown dropup btn-warning"><a href="#" id="myTabDrop2-1" class="dropdown-toggle" data-toggle="dropdown">Others <b class="caret"></b></a>
									<ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1">
										<li><a href="#dropdown2-1" tabindex="-1" data-toggle="tab">@Scooter</a></li>
										<li><a href="#dropdown2-2" tabindex="-1" data-toggle="tab">@Motorcycle</a></li>
									</ul>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		<div class="row">
			<div class="col-md-6">
				<div class="panel">
					<div class="tabbable tabs-left clearfix">
						<ul id="myTab1" class="nav nav-tabs">
							<li class="active bg-picton"><a href="#home3" data-toggle="tab">House & Lot</a></li>
							<li class="bg-picton"><a href="#profile3" data-toggle="tab">Condominium</a></li>
							<li class="bg-picton"><a href="#myTabDrop3" data-toggle="tab">Apartment</a></li>
						</ul>
						<div id="myTabContent" class="tab-content">
							<div class="tab-pane fade active in" id="home3">
								<!-- <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.</p> -->
								<?php echo Phalcon\Tag::image(array("themes/mybarangay1/img/realty.png", "alt" => "Properties Photo", "class" => "img-responsive")); ?>
							</div>
							<div class="tab-pane fade" id="profile3">
								<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee.</p>
							</div>
							<div class="tab-pane fade" id="myTabDrop3">
								<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone...</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel">
					<div class="tabbable tabs-right clearfix">
						<ul id="myTab1" class="nav nav-tabs">
							<li class="active bg-peach"><a href="#home4" data-toggle="tab">Gadgets</a></li>
							<li class="bg-peach"><a href="#profile4" data-toggle="tab">Computers</a></li>
							<li class="bg-peach"><a href="#myTabDrop4" data-toggle="tab">Appliances</a></li>
						</ul>
						<div id="myTabContent" class="tab-content">
							<div class="tab-pane fade active in" id="home4">
								<p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.</p>
							</div>
							<div class="tab-pane fade" id="profile4">
								<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee.</p>
							</div>
							<div class="tab-pane fade" id="myTabDrop4">
								<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone...</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
		$(document).ready(function(){
			$('.cancel').on('click', function() { 
				$('.cd-modal-close').trigger('click');
				$('.cd-modal-close')[0].click();
			});
		});
		
		function googleAuth(authResult) {
				var gData = authResult;
				var y = false;
			$('#signinButton').on('click', function() { 
				 y = true;
				 var authResult = gData;
									
				if (authResult['code'] && y == true) {
				    // Hide the sign-in button now that the user is authorized, for example:
				    $('#signinButton').attr('style', 'display: none');
				    //console.log(authResult);
				    // Send the code to the server
				    $.ajax({
				      type: 'POST',
				      url: 'member/loginWithGoogle/',
				      data: {code : authResult['code'], access_token : authResult['access_token']},
				      //processData: true
				      //contentType: 'application/octet-stream; charset=utf-8',
				      success: function(result) {
				      	var obj = jQuery.parseJSON( result );
				        // Handle or verify the server response if necessary.

				        // Prints the list of people that the user has allowed the app to know
				        // to the console.
				        //console.log(result['status']);
				        if(obj['status'] == 'OK') {
				        	window.location.href = "/mybarangay/";
				        }
				       
				      }
				      
				    });
				} else if (authResult['error']) {
				    // There was an error.
				    // Possible error codes:
				    //   "access_denied" - User denied access to your app
				    //   "immediate_failed" - Could not automatially log in the user
				    console.log('There was an error: ' + authResult['error']);
				}
			});	
		}
	
	</script>
