<section class="content">
  <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Add User</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <?php  echo Phalcon\Tag::form(array('admin/user/add', 'method' => 'post', 'enctype'=>'multipart/form-data')); ?>
                  <div class="box-body">
                    <div class="row">
                      <div class="col-md-10">
                        <div class="form-group">
                          <label for="exampleInputFile">Profile Pictrue</label>
                          <input name="profile_pic" type="file" id="exampleInputFile">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputEmail1">First Name</label>
                          <input name="first_name" type="text" class="form-control" id="exampleInputEmail1" placeholder="First name">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Middle Name</label>
                          <input name="middle_name" type="text" class="form-control" id="exampleInputEmail1" placeholder="Middle name">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Last Name</label>
                          <input name="last_name" type="text" class="form-control" id="exampleInputEmail1" placeholder="Last name">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Address</label>
                          <input name="street" type="text" class="form-control" id="exampleInputEmail1" placeholder="Street">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputEmail1">City</label>
                          <input name="city" type="text" class="form-control" id="exampleInputEmail1" placeholder="City">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Country</label>
                          <select name="country_id"  type="select" class="form-control">
                              <option value="">Select country</option>
                            <?php foreach ($countries as $key => $country) { ?>
                              <option value="<?php echo $country->id; ?>"><?php echo $country->country; ?></option>
                            <?php } ?>
                          </select>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Mobile</label>
                          <input name="mobile" class="form-control" id="exampleInputEmail1" placeholder="Enter mobile no">
                          </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Email</label>
                          <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="exampleInputPassword1">Password</label>
                          <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                        </div>
                      </div>
                    </div>
                  </div><!-- /.box-body -->

                  <div class="box-footer text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                <?php  echo Phalcon\Tag::endForm(); ?>
              </div><!-- /.box -->
            </div>
  </div>
</section>