<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html">My<b>Barangay</b></a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
    <div class="row">
      <div class="col-md-12">
        <?php $this->flash->output(); ?>
      </div>
    </div>
    <?php  echo Phalcon\Tag::form(array('admin/login', 'method' => 'post')); ?>
      <div class="form-group has-feedback">
        <input name="email" type="email" class="form-control" placeholder="Email" required />
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input name="password" type="password" class="form-control" placeholder="Password" required />
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">    
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>                        
        </div><!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div><!-- /.col -->
      </div>
    <?php  echo Phalcon\Tag::endForm(); ?>
    <a href="#">I forgot my password</a><br>

  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->