<div id="hoteloptions">
							<!-- hotel options -->
							<br>
							<table class="table-options" style="border: 1px solid black; ">
								<tr style="border: 1px solid black">
									<label>Can you tell us</label>
								</tr>
								
								<tr style="border: 1px solid black">
									<td><label>Wi-Fi  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="hotel_wifi" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_wifi" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_wifi" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Has TV  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="hotel_hastv" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_hastv" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_hastv" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>

								<tr style="border: 1px solid black;">
									<td>
										<label>Price Range</label>
									</td>
									<td style=" padding-top: 10px;">
										<div class="form-group form-group-sm">
											<select name="hotel_pricerange" style="height: 25px;width: 120px;" class="form-control">
											  <option value="inexpensive">Inexpensive</option>
											  <option value="moderate">Moderate</option>
											  <option value="pricey">Pricey</option>
											  <option value="ultra high-end">Ultra High-End</option>
											</select>
										</div>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Accepts Credit Cards  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="hotel_creditcard" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_creditcard" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_creditcard" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Parking    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="hotel_parking" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_parking" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_parking" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Bike Parking    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="hotel_bike_parking" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_bike_parking" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_bike_parking" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>

								<tr style="border: 1px solid black">
									<td><label>Good for Groups    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="hotel_groups" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_groups" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_groups" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								 <tr style="border: 1px solid black">
									<td><label>Good for Kids    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="hotel_kids" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_kids" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="hotel_kids" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								
							</table>
							<!-- end hotel options -->
							</div>
