<div id="artoptions">
							<!-- arts and entertainment -->
							<br>
							<table class="table-options" style="border: 1px solid black; ">
								<tr style="border: 1px solid black">
									<label>Can you tell us?</label>
								</tr>


								<tr style="border: 1px solid black">
									<td><label>Accepts Credit Cards  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="art_creditcard" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="art_creditcard" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="art_creditcard" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Parking    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="art_parking" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="art_parking" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="art_parking" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Bike Parking    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="art_bike_parking" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="art_bike_parking" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="art_bike_parking" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								
								 <tr style="border: 1px solid black">
									<td><label>Good for Kids    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="art_kids" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="art_kids" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="art_kids" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								
							</table>
							<!-- end arts and entertainment-->
							</div>
