<div id="spaoptions">
							<!-- beauty options -->
							<br>
							<table class="table-options" style="border: 1px solid black; ">
								<tr style="border: 1px solid black">
									<label>Beauty and Spas Review Options</label>
								</tr>

								<tr style="border: 1px solid black">
									<td><label>Wi-Fi  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="spa_wifi" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_wifi" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_wifi" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Has TV  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="spa_hastv" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_hastv" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_hastv" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>

								<tr style="border: 1px solid black;">
									<td>
										<label>Price Range</label>
									</td>
									<td style=" padding-top: 10px;">
										<div class="form-group form-group-sm">
											<select name="spa_pricerange" style="height: 25px;width: 120px;" class="form-control">
											  <option value="inexpensive">Inexpensive</option>
											  <option value="moderate">Moderate</option>
											  <option value="pricey">Pricey</option>
											  <option value="ultra high-end">Ultra High-End</option>
											</select>
										</div>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Accepts Credit Cards  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="spa_creditcard" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_creditcard" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_creditcard" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Parking    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="spa_parking" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_parking" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_parking" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Bike Parking    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="spa_bike_parking" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_bike_parking" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_bike_parking" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>

								<tr style="border: 1px solid black">
									<td><label>Appointments    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="spa_appointments" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_appointments" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_appointments" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								 <tr style="border: 1px solid black">
									<td><label>Good for Kids    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="spa_kids" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_kids" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="spa_kids" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								
							</table>
							<!-- end beauty options -->
							</div>