<div id="homeoptions">
							<!-- home services -->
							<br>
							<table class="table-options" style="border: 1px solid black; ">
								<tr style="border: 1px solid black">
									<label>Can you tell us?</label>
								</tr>
								
								

								<tr style="border: 1px solid black;">
									<td>
										<label>Price Range</label>
									</td>
									<td style=" padding-top: 10px;">
										<div class="form-group form-group-sm">
											<select name="home_pricerange" style="height: 25px;width: 120px;" class="form-control">
											  <option value="inexpensive">Inexpensive</option>
											  <option value="moderate">Moderate</option>
											  <option value="pricey">Pricey</option>
											  <option value="ultra high-end">Ultra High-End</option>
											</select>
										</div>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Accepts Credit Cards  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="home_creditcard" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="home_creditcard" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="home_creditcard" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Appointments    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="home_appointments" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="home_appointments" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="home_appointments" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								
							</table>
							<!-- end home services -->
							</div>
