<div id="foodoptions">
							<!-- food options -->
							<br>
							<table class="table-options" style="border: 1px solid black; ">
								<tr style="border: 1px solid black">
									<label>Can you tell us?</label>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Caters  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_caters" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_caters" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_caters" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Wi-Fi  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_wifi" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_wifi" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_wifi" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Has TV  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_hastv" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_hastv" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_hastv" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>

								<tr style="border: 1px solid black;">
									<td>
										<label>Price Range</label>
									</td>
									<td style=" padding-top: 10px;">
										<div class="form-group form-group-sm">
											<select name="food_pricerange" style="height: 25px;width: 120px;" class="form-control">
											  <option value="inexpensive">Inexpensive</option>
											  <option value="moderate">Moderate</option>
											  <option value="pricey">Pricey</option>
											  <option value="ultra high-end">Ultra High-End</option>
											</select>
										</div>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Accepts Credit Cards  </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_creditcard" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_creditcard" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_creditcard" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Parking    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_parking" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_parking" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_parking" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Bike Parking    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_bike_parking" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_bike_parking" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_bike_parking" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Attire    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_attire" id="inlineRadio1" value="casual"> casual
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_attire" id="inlineRadio2" value="dressy"> dressy
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_attire" id="inlineRadio3" value="format (jacket require)"> formal (jacket required)
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_attire" id="inlineRadio4" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Good for Groups    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_groups" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_groups" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_groups" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								 <tr style="border: 1px solid black">
									<td><label>Good for Kids    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_kids" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_kids" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_kids" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Takes Reservations    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_reservations" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_reservations" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_reservations" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Delivery    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_delivery" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_delivery" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_delivery" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Take Away    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_takeaway" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_takeaway" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_takeaway" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Waiter Service    </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_waiter" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_waiter" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_waiter" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Outdoor Seating   </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_outdoor" id="inlineRadio1" value="yes"> yes
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_outdoor" id="inlineRadio2" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_outdoor" id="inlineRadio3" value="not sure"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Good for     </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_goodfor" id="inlineRadio1" value="breakfast"> breakfast
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_goodfor" id="inlineRadio2" value="brunch"> brunch
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_goodfor" id="inlineRadio3" value="lunch"> lunch
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_goodfor" id="inlineRadio4" value="dinner"> dinner
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_goodfor" id="inlineRadio5" value="late_night"> late-night
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_goodfor" id="inlineRadio6" value="dessert"> dessert
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Alcohol   </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_alcohol" id="inlineRadio1" value="beer n' wine only"> beer & wine only 
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_alcohol" id="inlineRadio2" value="full bar"> full bar
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_alcohol" id="inlineRadio3" value="no"> no
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_alcohol" id="inlineRadio4" value="no"> not sure
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Noise Level   </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_noise" id="inlineRadio1" value="quiet"> quiet 
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_noise" id="inlineRadio2" value="average"> average
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_noise" id="inlineRadio3" value="loud"> loud
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_noise" id="inlineRadio4" value="very loud"> very loud
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_noise" id="inlineRadio5" value="no"> no
										</label>
									</td>
								</tr>
								<tr style="border: 1px solid black">
									<td><label>Ambience   </label></td>
									<td>
										<label class="radio-inline">
										  <input type="radio" name="food_ambience" id="inlineRadio1" value="hipster"> hipster 
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_ambience" id="inlineRadio2" value="casual"> casual
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_ambience" id="inlineRadio3" value="touristy"> touristy
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_ambience" id="inlineRadio4" value="trendy"> trendy
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_ambience" id="inlineRadio5" value="intimate"> intimate
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_ambience" id="inlineRadio6" value="romantic"> romantic
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_ambience" id="inlineRadio7" value="classy"> classy
										</label>
										<label class="radio-inline">
										  <input type="radio" name="food_ambience" id="inlineRadio8" value="upscale"> upscale
										</label>
									</td>
								</tr>
							</table>
							<!-- end food options -->
							</div>
