
<?php echo $this->tag->javascriptInclude("themes/customize/js/ckeditor/ckeditor.js"); ?>
>
<div class="container" id="container">
	<div class="col-md-12 bg-white">
		<div class="row">
			<br>
			<div class="col-md-12 bg-primary">
				<h1>Update Job</h1>
				<p>Please note: This job will not appear in search results until it has been approved by our moderators.</p>
			</div>
		</div>
		<div class="row">
			<br>
			<div class="col-md-3 profile-widget">
				<?php $this->partial("layouts/elements/profile_widget") ?>
			</div>
			<div class="col-md-6">
				<?php echo Phalcon\Tag::form(array("job/update/".$job->id, "method" => "post", "enctype"=>"multipart/form-data")); ?>
				  	<div class="col-md-12">
				  		<input name="id" type="text" class="hidden" value="<?php echo $job->id; ?>">
						<div class="form-group">
							<label>Position</label>
							<input name="position" type="text" class="form-control" value="<?php echo $job->position; ?>">
						</div>
						<div class="form-group">
							<label>Job Category</label>
							<select name="job_category_id"  type="select" class="form-control">
								<?php foreach ($jobCategories as $key => $jobCategory) { ?>
									<?php if($job->job_category_id == $jobCategory->id){ ?>
										<option value="<?php echo $jobCategory->id; ?>" selected><?php echo $jobCategory->name; ?></option>
									<?php } else { ?>
										<option value="<?php echo $jobCategory->id; ?>"><?php echo $jobCategory->name; ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</div>
						<div class="form-group">
							<label>Job Description</label>
							<textarea class="ckeditor form-control" name="job_description" rows="10"><?php echo $job->job_description; ?></textarea>
							
						</div>
						<div class="form-group">
							<label>Requirements</label>
							<textarea name="requirements" type="textarea" class="ckeditor form-control" placeHolder=""><?php echo $job->requirements; ?></textarea> 
						</div>
						<div class="form-group">
							<label>Benefits</label>
							<textarea name="benefits" type="textarea" class="ckeditor form-control" placeHolder=""><?php echo $job->benefits; ?></textarea> 
						</div>
						
						<div class="form-group">
							<label>How to apply</label>
							<textarea name="how_to_apply" type="textarea" class="ckeditor form-control" placeHolder=""><?php echo $job->how_to_apply; ?></textarea> 
						</div>
						<div class="form-group">
						  <div class="col-lg-12 text-center">
							<button type="submit" class="btn btn-primary">Update</button>
						  </div>
						</div>

				  	</div>
				
				<br>
			</div>
			<div class="col-md-3">
				<div class="col-md-12">
					<div class="form-group">
						<label>Company Logo</label>
						<div class="col-md-12">
							<?php echo Phalcon\Tag::image(array($jobLogo, 'class' => 'img-responsive img-rounded img-thumbnail')); ?>
							<br><br>
						</div>
						<input name="logo" type="file" class="form-control file" >
					</div>
					<div class="form-group">
						<div class="row">
							<div class="col-md-12">
								<label>Salary Range</label>
							</div>
						</div>
						<div class="row">
							<div class="col-md-5">
								<input name="salary_from" type="text" class="form-control" value="<?php echo $job->salary_from; ?>">
							</div>
							<div class="col-md-2 text-center">|</div>
							<div class="col-md-5">
								<input name="salary_to" type="text" class="form-control" value="<?php echo $job->salary_to; ?>">
							</div>
						</div>
					</div>
					<div class="form-group">
						<label>Company</label>
						<input name="company" type="text" class="form-control" value="<?php echo $job->company; ?>">
					</div>
					<div class="form-group">
						<label>Website</label>
						<input name="website" type="text" class="form-control" value="<?php echo $job->website; ?>">
					</div>
					<div class="form-group">
						<label>Telephone</label>
						<input name="telephone" type="text" class="form-control" value="<?php echo $job->telephone; ?>">
					</div>
					<div class="form-group">
						<label>Email</label>
						<input name="email" type="text" class="form-control" value="<?php echo $job->email; ?>">
					</div>
					<div class="form-group">
						<label>Address</label>
						<input name="street" type="text" class="form-control" value="<?php echo $job->street; ?>">
					</div>
					<div class="form-group">
						<label>City</label>
						<input name="city" type="text" class="form-control" value="<?php echo $job->city; ?>">
					</div>
					<div class="form-group">
						<label>Country</label>
						<select name="country_id"  type="select" class="form-control">
							<?php foreach ($countries as $key => $country) { ?>
								<?php if($job->country_id == $country->id){ ?>
									<option value="<?php echo $country->id; ?>" selected><?php echo $country->country; ?></option>
								<?php } else { ?>
									<option value="<?php echo $country->id; ?>"><?php echo $country->country; ?></option>
								<?php } ?>
							<?php } ?>
						</select>
					</div>
				</div>
				<?php echo Phalcon\Tag::endForm(); ?>
				<!-- <h1 class="text-danger"><strong>Trabaho</strong></h1>
				<h3>Get your job hiring listed in <span class="text-primary"><strong>MyBarangay</strong></span>.</h3>
				<div class="col-md-8 col-md-offset-3">
				<?php //echo Phalcon\Tag::image(array("themes/mybarangay1/img/biz/new_biz.jpg", 'class' => 'img-responsive img-rounded img-block')); ?>
				</div> -->
			</div>
		</div>
		<br><br>
	</div>
</div>

