<div class="container-fluid" style="background-color:#fff;padding:0px;">
<div id="myCarousel" class="carousel slide" data-ride="carousel" style="padding-bottom: 20px;">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active" style="height: 310px;">
          <img class="first-slide" src="http://touchechicago.com/wp-content/uploads/2013/10/Grey-Background-BLANK.png" alt="First slide">
          <div class="container" style="padding-bottom: 20px;">
            <div class="carousel-caption">
              <h1>Featured Ad</h1>
              <p>coming soon</p>
              
            </div>
          </div>
        </div>
        <div class="item" style="height: 310px;">
          <img class="second-slide" src="http://touchechicago.com/wp-content/uploads/2013/10/Grey-Background-BLANK.png" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Featured Ad</h1>
      		<p>coming soon</p>
            
            </div>
          </div>
        </div>
        <div class="item" style="height: 310px;">

          <img class="third-slide" src="http://touchechicago.com/wp-content/uploads/2013/10/Grey-Background-BLANK.png" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Featured Ad</h1>
            	<p>coming soon</p>
              <!--<p><a class="btn btn-lg btn-primary" href="#" role="button">see more</a></p>-->
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
</div>
