
<div class="jumbotron col-md-12" style="height: 250px;">
      <div class="container">
          <!--<div class="container">
            <h1 class="text-center feat" style="margin-top:-20px;">Featured Ads</h1>
          </div>-->
        <input id="chkpoint" type="hidden" />
        <div class="row">
          <div class="col-md-12">
            <div class="row">
           <!-- start 1-->
              <div id="1"  class="hideable col-md-10 col-md-push-1 hideable" style="background-color: #003082;height: 160px;padding-top: 10px;width: 82%;">
              <!-- <br/> -->
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                    <!-- cars and trucks -->
      <img src="http://jobstar.asia/uploads/thumbs/20140529074205-city-of-dreams-logo1.jpg">

                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
      <img src="http://upload.wikimedia.org/wikipedia/en/archive/9/9e/20110219025441!Megamall_01.jpg">
                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                      <!--<h2 class="feat">Recent Real Estate Post</h2>-->
      <img src="http://bccondos.net/images/2013/05/28/capture.png">
 
                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                      <!--<h2 class="text-center feat">Recent Thing Post</h2>-->
            <img src="http://www.weddingstv.com.ph/wp-content/uploads/2014/02/Solaire_Resort_logo.png">
                    
                    </div>
                  </div>
                </div>
              </div>
              <!-- end 1-->
              <!-- start 2-->
              <div id="2"  class="hideable col-md-10 col-md-push-1" style="background-color: #003082;height: 160px;padding-top: 10px;width: 82%;">
              <!-- <br/> -->
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                    <!-- cars and trucks -->
          <img src="http://2.bp.blogspot.com/_BGCdVUeN4To/S_RqYC-7SMI/AAAAAAAAAcU/lq3EcSwF9cU/s1600/MSI-Camellia_Hospice_RGB_REG.jpg">
                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
   <img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTJkARurxfwkknEFSk32GksSQoPZIAlreu5Hg6goWb06j-SYoRZnw">
      
                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                      <!--<h2 class="feat">Recent Real Estate Post</h2>-->
          <img src="http://hawkbag.com/wp-content/uploads/2014/09/FT.jpg">
                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                      <!--<h2 class="text-center feat">Recent Thing Post</h2>-->
     <img src="http://bccondos.net/images/2013/05/28/capture.png">
            
                    </div>
                  </div>
                </div>
              </div>
              <!-- end 2-->
              <!-- start 3-->
              <div id="3"  class="hideable col-md-10 col-md-push-1" style="background-color: #003082;height: 160px;padding-top: 10px;width: 82%;">
              <!-- <br/> -->
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                    <!-- cars and trucks -->
      <img src="http://jobstar.asia/uploads/thumbs/20140529074205-city-of-dreams-logo1.jpg">

                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
      <img src="http://upload.wikimedia.org/wikipedia/en/archive/9/9e/20110219025441!Megamall_01.jpg">
                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                      <!--<h2 class="feat">Recent Real Estate Post</h2>-->
      <img src="http://bccondos.net/images/2013/05/28/capture.png">
 
                    </div>
                    <div class="col-md-3 custom-thumbnail" style="border: 1px solid black; height: 140px;">
                      <!--<h2 class="text-center feat">Recent Thing Post</h2>-->
            <img src="http://www.weddingstv.com.ph/wp-content/uploads/2014/02/Solaire_Resort_logo.png">
                  
                    </div>
                  </div>
                </div>
              </div>
              <!-- end 3-->
            </div>
          </div>
        </div>
        <div class="row" style="padding-top: 10px;">
          <div class="col-md-6 col-md-offset-5" style="padding-left: 51px;"><?php $this->flash->output(); ?>
    <div class="btn-group" role="group" aria-label="...">
      <button id="prev" type="button" class="btn btn-danger"><i class="fa fa-arrow-left"></i>
  </button>
      <button id="next" type="button" class="btn btn-danger"><i class="fa fa-arrow-right"></i>
  </button>
    </div>
</div>
  
        </div>
      </div>
    </div>

