<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>MyBarangay</title>

    <!-- Bootstrap core CSS -->
    <?php echo $this->tag->stylesheetLink("themes/customize/css/bootstrap.min.css"); ?>
    <!-- Custom styles for this template -->
    <?php echo $this->tag->stylesheetLink("themes/customize/css/customize.css"); ?>

  
  </head>

  <body style="background-color:#f5f5f5">

    <nav class="navbar navbar navbar-fixed-top" style="border-bottom:1px solid #2e6da4;background-color:#f5f5f5!important;height:100px;--webkit-box-shadow: 1px 4px 19px -8px rgba(59,59,59,1);
-moz-box-shadow: 1px 4px 19px -8px rgba(59,59,59,1);
box-shadow: 1px 4px 19px -8px rgba(59,59,59,1;">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        <div class="row">
            <div class="col-md-4">
              <a class="navbar-brand" href="#">
                <?php echo Phalcon\Tag::image(array("themes/customize/img/logo1.png",'alt' => 'Logo','class' =>'logo-head'));?>
              </a>
            </div>
            <div class="col-md-6" style="margin-left:-50px;" >
              <div class="row">
                <div class="col-md-12">
                     
                  <form class="form-inline" style="border:5px solid #2e6da4;margin-top:5px;margin-bottom:3px;background-color:#2e6da4">
                    <div class="form-group" style="border:5px solid #2e6da4;">
                      <label class="sr-only" for="exampleInputEmail3">Email address</label>
                      <input type="email" class="form-control" id="exampleInputEmail3" style="width:280px;" placeholder="Find?">
                    </div>
                    <div class="form-group" style="border:5px solid #2e6da4;margin-left:-5px!important">
                      <label class="sr-only" for="exampleInputPassword3">Password</label>
                      <input type="text" class="form-control" id="exampleInputPassword3" style="width:280px;" placeholder="Near?">
                    </div>
                    <button type="submit" class="btn btn-danger" style="margin:0!important;">
                      <span class="glyphicon glyphicon-search" style="font-size:20px;" aria-hidden="true"></span>
                    </button>
                  </form>
              
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                    <ul class="nav nav-pills">
                      <li><a href="#"><strong>Home</strong></a></li>
                      <li><a href="#"><strong>Chatter</strong></a></li>
                      <li><a href="#"><strong>Write a Review</strong></a></li>
                      <li><a href="#"><strong>Classifieds</strong></a></li>
                      <li><select class="form-control">
                        <option>--------------SEARCH----------</option>
                      </select></li>
                    </ul>
                </div>
              </div>
                
            </div>
            <div class="col-md-2">
                <div class="row pull-left">
                      <img src="http://placehold.it/60x60" alt="..." class="img-circle" style="padding:10px;"> <br/>
                      <span><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name</strong></span>
                </div>
            </div>
        </div>
        
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron1">
      <div class="container" style="background-color:#fff;margin-top:70px;border:1px solid #ccc;">

       <div class="row">
          <div class="col-md-3"><!-- profile column -->
            <div style="height:600px;border:1px solid #efefef;border-radius:10px;margin:10px;">
              <div class="row" style="margin:5px;">
                <div>
                  <center>
                    <img src="http://placehold.it/200x200" alt="..." class="img-thumbnail">    
                  </center>
                </div>
              </div>
              <div class="row">
                  <div class="col-md-4">
                    <img src="http://placehold.it/60x60" alt="..."  style="margin-left:20px;">    
                  </div>
                  <div class="col-md-4">
                    <img src="http://placehold.it/60x60" alt="..." class="img">    
                  </div>
                  <div class="col-md-4">
                    <img src="http://placehold.it/60x60" alt="..." style="margin-left:-20px;">    
                  </div>
              </div>
              <div class="row">
                <center>
                  <h4>Name</h4>
                </center>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <ul class="list-group">
                    <li class="list-group-item">
                      <span class="badge">14</span>
                      Cras justo odio
                    </li>
                    <li class="list-group-item">
                      <span class="badge">14</span>
                      Cras justo odio
                    </li>
                    <li class="list-group-item">
                      <span class="badge">14</span>
                      Cras justo odio
                    </li>
                  </ul>
                </div>
              </div>
              <div class="row">
                <div style="margin-left:15px;width:89%;position:relative;border:1px solid #ccc;border-radius:10px;padding:10px;">
                  <p>Description,descdescdes<br/>
                  cdescdescdescdesc</p>
                </div>
              </div>

            </div>

            <div style="height:300px;border:1px solid #efefef;margin:10px;background-color:#ccc">
              <span class="danger text-center">
                <h2>Container</h2>
              </span>
            </div>
          </div><!-- profile column -->
          <div class="col-md-6"> <!-- post div -->

          </div> <!-- post div  -->

          <div class="col-md-3"> <!-- friends column -->
            <div style="height:400px;border:1px solid #efefef;margin:10px;background-color:#fbfbfb;padding:5px;">
                <div class="row">
                    <div class="col-md-6">
                      <span style="color:#dc0002;float:left;margin-left:10px;">Friends</span>
                    </div>
                    <div class="col-md-6">
                      <span style="color:#dc0002;float:right;margin-right:10px;">721</span>
                    </div>
                </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <img src="http://placehold.it/50x50" alt="..." class="img">
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                    </div>
                  </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <img src="http://placehold.it/50x50" alt="..."  class="img">
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                    </div>
                  </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <img src="http://placehold.it/50x50" alt="..." class="img">
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                    </div>
                  </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <img src="http://placehold.it/50x50" alt="..." class="img">
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                      <img src="http://placehold.it/50x50" alt="..." class="img">    
                    </div>
                  </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <button class="btn btn-danger">View All</button>
                    </div>
                  </div>

            </div>
              <div style="height:400px;border:1px solid #efefef;margin:10px;background-color:#fbfbfb;padding:5px;">
                <div class="row">
                    <div class="col-md-6">
                      <span style="color:#dc0002;float:left;margin-left:10px;">Compliments</span>
                    </div>
                    <div class="col-md-6">
                      <span style="color:#dc0002;float:right;margin-right:10px;">721</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                      <span style="color:#dc0002;float:left;margin-left:10px;">&nbsp;</span>
                    </div>
                    <div class="col-md-6">
                      <span style="color:#dc0002;float:right;margin-right:10px;">&nbsp;</span>
                    </div>
                </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <div class="media">
                        <div class="media-left">
                          <a href="#">
                            <img class="media-object" src="http://placehold.it/50x50" alt="...">
                          </a>
                        </div>
                        <div class="media-body">
                          <h5 class="media-heading"><strong>User Name</strong></h5>
                          <p style="font-size:9px;">Hi nice review on that section!<br/>
                          10/01/2015 9:15:00pm</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <div class="media">
                        <div class="media-left">
                          <a href="#">
                            <img class="media-object" src="http://placehold.it/50x50" alt="...">
                          </a>
                        </div>
                        <div class="media-body">
                          <h5 class="media-heading"><strong>User Name</strong></h5>
                          <p style="font-size:9px;">Hi nice review on that section!<br/>
                          10/01/2015 9:15:00pm</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <div class="media">
                        <div class="media-left">
                          <a href="#">
                            <img class="media-object" src="http://placehold.it/50x50" alt="...">
                          </a>
                        </div>
                        <div class="media-body">
                          <h5 class="media-heading"><strong>User Name</strong></h5>
                          <p style="font-size:9px;">Hi nice review on that section!<br/>
                          10/01/2015 9:15:00pm</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <div class="media">
                        <div class="media-left">
                          <a href="#">
                            <img class="media-object" src="http://placehold.it/50x50" alt="...">
                          </a>
                        </div>
                        <div class="media-body">
                          <h5 class="media-heading"><strong>User Name</strong></h5>
                          <p style="font-size:9px;">Hi nice review on that section!<br/>
                          10/01/2015 9:15:00pm</p>
                        </div>
                      </div>
                    </div>
                  </div>
                 
                  <div class="row" style="margin-left:10px;margin-bottom:10px;">
                    <div class="col-md-12" style="padding:0!important;">
                      <button class="btn btn-danger">View All</button>
                    </div>
                  </div>

            </div>
            <div style="height:300px;border:1px solid #efefef;margin:10px;background-color:#ccc">
              <span class="danger text-center">
                <h2>Container</h2>
              </span>
            </div>


          </div><!-- friends column -->

       </div>

      </div>
    </div>

     

    


    <div class="container-fluid" style="background-color:#09398B;margin-bottom:-20px!important;height:100px;">
      <div class="container" style="color:#fff;">
      <br/>
          <footer>
            <p><strong>&copy; Copyright MyBarangay 2015</strong></p>
          </footer>
           <div class="pull-left">
            <a href="#"><img src="http://placehold.it/40x40" class="circle"></a>
            <a href="#"><img src="http://placehold.it/40x40" class="circle"></a>
            <a href="#"><img src="http://placehold.it/40x40" class="circle"></a>
            <a href="#"><img src="http://placehold.it/40x40" class="circle"></a>
            <a href="#"><img src="http://placehold.it/40x40" class="circle"></a>
          </div>
          <ul class="nav nav-pills pull-right">
            <li><a style="color:#fff!important;"href="#">About</a></li>
            <li><a style="color:#fff!important;"href="#">Contact Us</a></li>
            <li><a style="color:#fff!important;"href="#">Disclaimer</a></li>
          </ul>
          <br/>
 
      </div>
    
    </div> <!-- /container -->

    <?php echo $this->tag->javascriptInclude("themes/customize/js/jquery.min.js"); ?>
    <?php echo $this->tag->javascriptInclude("themes/customize/js/bootstrap.min.js"); ?>
  </body>
</html>
