  <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron col-md-12">
      <div class="container">
          <div class="container">
            <h1 class="text-center feat" style="margin-top:-20px;">Featured Classifieds</h1>
          </div>
        
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-10 col-md-push-1" style="background-color: #fff;height: 280px;padding-top: 10px;width: 82%;">
              <!-- <br/> -->
                <table class="" width="100%" >
                  
                  <tr>
                    <?php foreach($realties as $key => $realty){ ?>
                    <td style="border-top:0!important;"> <!--former size of the image placeholder is 275x150-->
                     <?php $realtyImg = 'http://placehold.it/230x130'; ?>
                      <?php 
                      	 if(count($realty->RealtyPhotos)){ $realtyImg = $realty->RealtyPhotos[0]->file_path.$realty->RealtyPhotos[0]->filename; }  
                       ?>
                      <?php echo Phalcon\Tag::linkTo(array('real_estate/view/'.$realty->id, Phalcon\Tag::image(array($realtyImg, 'class' => 'img-responsive img-thumbnail ads_img', 'alt' => $realty->name)))); ?>
                      <p class="text-center"><?php echo Phalcon\Tag::linkTo(array('real_estate/view/'.$realty->id, $realty->name, 'class' => 'text-primary thingName')); ?></p>
                      <h5 class="text-center text-danger price"><?php echo $realty->RealtyCategories->name; ?></h5>
                    </td>
                    <?php } ?>
                  </tr>
                  <tr>
                    <?php foreach($jobs as $key => $job){ ?>
                    <td style="border-top:0!important;"> <!--former size of the image placeholder is 275x150-->
                     <?php $jobImg = 'http://placehold.it/220x130'; ?>
                      <?php 
                        if(count($job->JobLogos)){ $jobImg = $job->JobLogos[0]->file_path.$job->JobLogos[0]->filename; } 
                       ?>
                      <?php //echo Phalcon\Tag::image(array($jobImg, 'class' => 'img-responsive img-thumbnail ads_img', 'alt' => $job->position)); ?>
                      <?php echo Phalcon\Tag::linkTo(array('job/view/'.$job->id, Phalcon\Tag::image(array($jobImg, 'class' => 'img-responsive img-thumbnail ads_img', 'alt' => $job->position)))); ?>
                      <p class="text-center"><?php echo Phalcon\Tag::linkTo(array('job/view/'.$job->id, $job->position, 'class' => 'text-primary thingName')); ?></p>
                      <h5 class="text-center text-danger price"><?php echo $job->company; ?></h5>
                    </td>
                    <?php } ?>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

      <!-- <h3 class="text-danger text-center"> 
        <strong>Isang Mundo. Isang wika. Isang barangay<br/>
        Tuloy po kayo, Welcome Home.</strong>
      </h3> -->
      <!-- <br/> -->
      <div class="container-fluid" style="background-color:#fff;padding:0px;">

        <div class="navPillsDiv col-md-12">
        <div class="container" style="width:1200px;">
          <ul class="nav nav-tabs nav-justified" style="margin-top:4px;">
          <li role="presentation" class="active"><a href="#auto" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Automotive</strong></a></li>
          <li role="presentation"><a href="#community" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Community</strong></a></li>
          <li role="presentation"><a href="#food" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Food</strong></a></li>
          <li role="presentation"><a href="#hb" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Health&nbsp;&&nbsp;Beauty</strong></a></li>
          <li role="presentation"><a href="#hs" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Home&nbsp;&&nbsp;Services</strong></a></li>
          <li role="presentation"><a href="#pf" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Profesional & Financial</strong></a></li>
          <li role="presentation"><a href="#ht" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Hotels&nbsp;&&nbsp;Travel</strong></a></li>
          <li role="presentation"><a href="#re" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Real&nbsp;&nbsp;Estate</strong></a></li>
          <li role="presentation"><a href="#shopping" class="menu_button" role="tab" data-toggle="tab"><strong class="navPillsA">Shopping</strong></a></li>
        </ul>
        </div>

        <div class="tab-content remark_div col-md-12" style="padding:0px;">
              <!-- AUTO -->
              <div class="tab-pane fade fade in active" id="auto">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="container">
                    <div class="col-md-9">
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $bizFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(isset($autoBizFeatList[0]->BusinessImages[0]->filename)) {
                                      $autoBizFeatLatestPic = count($autoBizFeatList[0]->BusinessImages) - 1;
                                      $bizFeaturedImg = $autoBizFeatList[0]->BusinessImages[$autoBizFeatLatestPic]->file_path.$autoBizFeatList[0]->BusinessImages[$autoBizFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($bizFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$autoBizFeatList[0]->id, '<span class=""></span>'.$autoBizFeatList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($businessFeatured[0]->street) || ($autoBizFeatList[0]->street != '') ? $autoBizFeatList[0]->street.', '.$autoBizFeatList[0]->city.', '.$autoBizFeatList[0]->Countries->country : 'No address Info'); ?></p>
                              <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $autoBizFeatList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          }                 
                                        
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                        <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                              </div>  
                            </div>
                          </div>
                      </div>

                      <div class="width100">
                        <?php foreach ($autoBizList as $key => $biz) { ?>
                          <?php if($key <= 3 && $key != 0) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                                <?php $businessLastImg = 'http://placehold.it/220x120'; ?>
                              <?php //foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $latestPicKey = count($biz->BusinessImages) - 1;
                                  if($latestPicKey >= 0){
                                    $businessLastImg = $biz->BusinessImages[$latestPicKey]->file_path.$biz->BusinessImages[$latestPicKey]->filename;              }
                               //} ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street != '') ? $biz->street.', '.$biz->city.', '.$biz->Countries->country : 'No Address Info'); ?></p>
                                
                                <div class="rating1" >
                                        <?php
                                              
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                    </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                     
                     <div class="width100">
                        <?php foreach ($autoBizList as $key => $biz) { ?>
                          <?php if($key > 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street != '') ? $biz->street.', '.$biz->city.', '.$biz->Countries->country : 'No Address Info'); ?></p>
                                
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                      <span class="pull-right"><strong><a href="#" style="color:red!important">See More....</a></strong></span>
                    </div>
                    <div class="col-md-3">
                      <div class="topDealsContainer">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row topDealsName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row topDealsName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row topDealsName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row topDealsName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                      </div>

                      <div class="latestListContainer">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row latestListName" style="">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row latestListName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row latestListName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row latestListName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div class="todayInTalkContainer">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row todayInTalkName" style="">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row todayInTalkName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row todayInTalkName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row todayInTalkName">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>
              <!-- COMMUNITY -->
              <div class="tab-pane fade" id="community">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9">
                    <?php if(count($CommunityBizList) > 0){ ?>
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $bizFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(isset($CommunityBizList->BusinessImages[0]->filename)) {
                                      $communityBizFeatLatestPic = count($CommunityBizList[0]->BusinessImages) - 1;
                                      $bizFeaturedImg = $CommunityBizList[0]->BusinessImages[$communityBizFeatLatestPic]->file_path.$CommunityBizList[0]->BusinessImages[$communityBizFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($bizFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$CommunityBizList[0]->id, '<span class=""></span>'.$CommunityBizList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($CommunityBizList[0]->street) || ($CommunityBizList[0]->street = '') ? $CommunityBizList[0]->street : 'No Street Info'); ?></p>
                              <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $CommunityBizList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          }                 
                                        
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                        <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                              </div>  
                            </div>
                          </div>
                      </div>

                      <div class="width100">
                        <?php foreach ($CommunityBizList as $key => $biz) { ?>
                          <?php if($key < 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                                <?php $businessLastImg = 'http://placehold.it/220x120'; ?>
                              <?php //foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $latestPicKey = count($biz->BusinessImages) - 1;
                                  if($latestPicKey >= 0){
                                    $businessLastImg = $biz->BusinessImages[$latestPicKey]->file_path.$biz->BusinessImages[$latestPicKey]->filename;              }
                               //} ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street: 'No Street Info'); ?></p>
                                <div class="rating1" >
                                        <?php
                                              
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                    </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                     
                     <div class="width100">
                        <?php foreach ($CommunityBizList as $key => $biz) { ?>
                          <?php if($key > 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                      <span class="pull-right"><strong><a href="" style="color:red!important">See More....</a></strong></span>
                    <?php } ?>
                    </div>
                    <div class="col-md-3">
                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                        

                         

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>

              <!-- FOOD -->
              <div class="tab-pane fade" id="food">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9">
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $foodFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(isset($FoodBizList->BusinessImages[0]->filename)) {
                                      $foodFeatLatestPic = count($FoodBizList[0]->BusinessImages) - 1;
                                      $foodFeaturedImg = $FoodBizList[0]->BusinessImages[$foodFeatLatestPic]->file_path.$FoodBizList[0]->BusinessImages[$foodFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($foodFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$FoodBizList[0]->id, '<span class=""></span>'.$FoodBizList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($FoodBizList[0]->street) || ($FoodBizList[0]->street = '') ? $FoodBizList[0]->street : 'No Street Info'); ?></p>
                                <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $FoodBizList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          } 
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                </div>
                            </div>
                          </div>
                      </div>

                      <div class="row">

                        <div class="width100">
                        <?php foreach ($FoodBizList as $key => $biz) { ?>
                          <?php if($key < 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                
                               <div class="rating1" >
                                        <?php
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                    </div>
                                </div>
                              </div>
                            </div>
                            <?php } ?> 
                          <?php } ?> 
                        </div>
                      </div>
                     
                     <div class="row">
                        <div class="width100">
                        <?php foreach ($FoodBizList as $key => $biz) { ?>
                          <?php if($key >= 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <?php } ?> 
                          <?php } ?> 
                        </div>
                      </div>
                      <span class="pull-right"><strong><a href="" style="color:red!important">See More....</a></strong></span>
                    </div>
                    <div class="col-md-3">
                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                        

                         

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>

              <!-- HEALTH & BEAUTY -->
              <div class="tab-pane fade" id="hb">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9">
                    <?php if(count($HBeautyBizList)>0){ ?>
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $bizFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(isset($HBeautyBizList->BusinessImages[0]->filename)) {
                                      $communityBizFeatLatestPic = count($HBeautyBizList[0]->BusinessImages) - 1;
                                      $bizFeaturedImg = $HBeautyBizList[0]->BusinessImages[$communityBizFeatLatestPic]->file_path.$HBeautyBizList[0]->BusinessImages[$communityBizFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($bizFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$HBeautyBizList[0]->id, '<span class=""></span>'.$HBeautyBizList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($HBeautyBizList[0]->street) || ($HBeautyBizList[0]->street = '') ? $HBeautyBizList[0]->street : 'No Street Info'); ?></p>
                              <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $HBeautyBizList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          }                 
                                        
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                        <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                              </div>  
                            </div>
                          </div>
                      </div>

                      <div class="width100">
                        <?php foreach ($HBeautyBizList as $key => $biz) { ?>
                          <?php if($key < 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                                <?php $businessLastImg = 'http://placehold.it/220x120'; ?>
                              <?php //foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $latestPicKey = count($biz->BusinessImages) - 1;
                                  if($latestPicKey >= 0){
                                    $businessLastImg = $biz->BusinessImages[$latestPicKey]->file_path.$biz->BusinessImages[$latestPicKey]->filename;              }
                               //} ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street: 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                        <?php
                                              
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                    </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                     
                     <div class="width100">
                        <?php foreach ($HBeautyBizList as $key => $biz) { ?>
                          <?php if($key > 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                      <span class="pull-right"><strong><a href="" style="color:red!important">See More....</a></strong></span>
                      <?php } ?>
                    </div>
                    <div class="col-md-3">
                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                        

                         

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>

              <!-- HOME & SERVICES -->
              <div class="tab-pane fade" id="hs">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9">
                    <?php if(count($HServBizList)>0){ ?>
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $bizFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(isset($HServBizList->BusinessImages[0]->filename)) {
                                      $communityBizFeatLatestPic = count($HServBizList[0]->BusinessImages) - 1;
                                      $bizFeaturedImg = $HServBizList[0]->BusinessImages[$communityBizFeatLatestPic]->file_path.$HServBizList[0]->BusinessImages[$communityBizFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($bizFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$HServBizList[0]->id, '<span class=""></span>'.$HServBizList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($HServBizList[0]->street) || ($HServBizList[0]->street = '') ? $HServBizList[0]->street : 'No Street Info'); ?></p>
                              <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $HServBizList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          }                 
                                        
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                        <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                              </div>  
                            </div>
                          </div>
                      </div>

                      <div class="width100">
                        <?php foreach ($HServBizList as $key => $biz) { ?>
                          <?php if($key < 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                                <?php $businessLastImg = 'http://placehold.it/220x120'; ?>
                              <?php //foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $latestPicKey = count($biz->BusinessImages) - 1;
                                  if($latestPicKey >= 0){
                                    $businessLastImg = $biz->BusinessImages[$latestPicKey]->file_path.$biz->BusinessImages[$latestPicKey]->filename;              }
                               //} ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street: 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                        <?php
                                              
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                    </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                     
                     <div class="width100">
                        <?php foreach ($HServBizList as $key => $biz) { ?>
                          <?php if($key > 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                      <span class="pull-right"><strong><a href="" style="color:red!important">See More....</a></strong></span>
                      <?php } ?>
                    </div>
                    <div class="col-md-3">
                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                        
                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>

              <!-- PROFESIONAL & FINANCIAL -->
              <div class="tab-pane fade" id="pf">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9">
                    <?php if(count($FinBizList)>0){ ?>
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $bizFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(count($FinBizList[0]->BusinessImages)) {
                                      $communityBizFeatLatestPic = count($FinBizList[0]->BusinessImages) - 1;
                                      $bizFeaturedImg = $FinBizList[0]->BusinessImages[$communityBizFeatLatestPic]->file_path.$FinBizList[0]->BusinessImages[$communityBizFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($bizFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$FinBizList[0]->id, '<span class=""></span>'.$FinBizList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($FinBizList[0]->street) || ($FinBizList[0]->street = '') ? $FinBizList[0]->street : 'No Street Info'); ?></p>
                              <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $FinBizList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          }                 
                                        
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                        <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                              </div>  
                            </div>
                          </div>
                      </div>

                      <div class="width100">
                        <?php foreach ($FinBizList as $key => $biz) { ?>
                          <?php if($key < 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                                <?php $businessLastImg = 'http://placehold.it/220x120'; ?>
                              <?php //foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $latestPicKey = count($biz->BusinessImages) - 1;
                                  if($latestPicKey >= 0){
                                    $businessLastImg = $biz->BusinessImages[$latestPicKey]->file_path.$biz->BusinessImages[$latestPicKey]->filename;              }
                               //} ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street: 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                        <?php
                                              
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                    </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                     
                     <div class="width100">
                        <?php foreach ($FinBizList as $key => $biz) { ?>
                          <?php if($key > 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                      <span class="pull-right"><strong><a href="" style="color:red!important">See More....</a></strong></span>
                      <?php } ?>
                    </div>
                    <div class="col-md-3">
                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                        

                         

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>

              <!-- HOTEL & TRAVEL -->
              <div class="tab-pane fade" id="ht">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9">
                    <?php if(count($HTravelBizList)>0){ ?>
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $bizFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(isset($HTravelBizList->BusinessImages[0]->filename)) {
                                      $communityBizFeatLatestPic = count($HTravelBizList[0]->BusinessImages) - 1;
                                      $bizFeaturedImg = $HTravelBizList[0]->BusinessImages[$communityBizFeatLatestPic]->file_path.$HTravelBizList[0]->BusinessImages[$communityBizFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($bizFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$HTravelBizList[0]->id, '<span class=""></span>'.$HTravelBizList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($HTravelBizList[0]->street) || ($HTravelBizList[0]->street = '') ? $HTravelBizList[0]->street : 'No Street Info'); ?></p>
                              <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $HTravelBizList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          }                 
                                        
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                        <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                              </div>  
                            </div>
                          </div>
                      </div>

                      <div class="width100">
                        <?php foreach ($HTravelBizList as $key => $biz) { ?>
                          <?php if($key < 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                                <?php $businessLastImg = 'http://placehold.it/220x120'; ?>
                              <?php //foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $latestPicKey = count($biz->BusinessImages) - 1;
                                  if($latestPicKey >= 0){
                                    $businessLastImg = $biz->BusinessImages[$latestPicKey]->file_path.$biz->BusinessImages[$latestPicKey]->filename;              }
                               //} ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street: 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                        <?php
                                              
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                    </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                     
                     <div class="width100">
                        <?php foreach ($HTravelBizList as $key => $biz) { ?>
                          <?php if($key > 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                      <span class="pull-right"><strong><a href="" style="color:red!important">See More....</a></strong></span>
                      <?php } ?>
                    </div>
                    <div class="col-md-3">
                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                        

                         

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>

              <!-- REAL ESTATE -->
              <div class="tab-pane fade" id="re">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9">
                    <?php if(count($RealtyBizList)>0){ ?>
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $bizFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(isset($RealtyBizList->BusinessImages[0]->filename)) {
                                      $communityBizFeatLatestPic = count($RealtyBizList[0]->BusinessImages) - 1;
                                      $bizFeaturedImg = $RealtyBizList[0]->BusinessImages[$communityBizFeatLatestPic]->file_path.$RealtyBizList[0]->BusinessImages[$communityBizFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($bizFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$RealtyBizList[0]->id, '<span class=""></span>'.$RealtyBizList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($RealtyBizList[0]->street) || ($RealtyBizList[0]->street = '') ? $RealtyBizList[0]->street : 'No Street Info'); ?></p>
                              <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $RealtyBizList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          }                 
                                        
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                        <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                              </div>  
                            </div>
                          </div>
                      </div>

                      <div class="width100">
                        <?php foreach ($RealtyBizList as $key => $biz) { ?>
                          <?php if($key < 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                                <?php $businessLastImg = 'http://placehold.it/220x120'; ?>
                              <?php //foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $latestPicKey = count($biz->BusinessImages) - 1;
                                  if($latestPicKey >= 0){
                                    $businessLastImg = $biz->BusinessImages[$latestPicKey]->file_path.$biz->BusinessImages[$latestPicKey]->filename;              }
                               //} ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street: 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                        <?php
                                              
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                    </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                     
                     <div class="width100">
                        <?php foreach ($RealtyBizList as $key => $biz) { ?>
                          <?php if($key > 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                      <span class="pull-right"><strong><a href="" style="color:red!important">See More....</a></strong></span>
                      <?php } ?>
                    </div>
                    <div class="col-md-3">
                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                        

                         

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>

              <!-- SHOPPING -->
              <div class="tab-pane fade" id="shopping">
                <div class="container" style="padding:10px;">
                  <div class="row" style="margin:5px ">
                    <div class="col-md-12">
                      <form class="form-inline text-center">
                        <div class="form-group">
                          <select class="form-control">
                          <option>Sub-Category</option></select>
                        </div>
                        <div class="form-group">
                          <select class="form-control">
                          <option>Location</option></select>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                      </form>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9">
                    <?php if(count($ShoppingBizList)>0){ ?>
                      <div class="featuredBusiness">
                          <div class="media">
                            <div class="media-left" style="min-width:500px;">
                              <a href="#">
                                  <?php $bizFeaturedImg = 'http://placehold.it/600x250'; ?>
                                  <?php 
                                    if(isset($ShoppingBizList->BusinessImages[0]->filename)) {
                                      $communityBizFeatLatestPic = count($ShoppingBizList[0]->BusinessImages) - 1;
                                      $bizFeaturedImg = $ShoppingBizList[0]->BusinessImages[$communityBizFeatLatestPic]->file_path.$ShoppingBizList[0]->BusinessImages[$communityBizFeatLatestPic]->filename;
                                    } 
                                  ?>
                                  <?php echo Phalcon\Tag::image(array($bizFeaturedImg, 'class' => 'img-responsive img-rounded', 'style' => 'height:250px!important;width:500px!important')); ?>
                              </a>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading">
                              <?php echo Phalcon\Tag::linkTo(array('business/view/'.$ShoppingBizList[0]->id, '<span class=""></span>'.$ShoppingBizList[0]->name, 'class' => 'text-primary')); ?></h4>
                              <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($ShoppingBizList[0]->street) || ($ShoppingBizList[0]->street = '') ? $ShoppingBizList[0]->street : 'No Street Info'); ?></p>
                              <div class="rating1" >
                                  <?php
                                          $arrayRate = explode('.', $ShoppingBizList[0]->average_rate);
                                          if(isset($arrayRate[1])){
                                            if($arrayRate[1] > 5) { 
                                              $arrayRate[0]++; $arrayRate[1] = 0; 
                                            }
                                            if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                               $arrayRate[1] = 5; 
                                            }
                                          } else {
                                            $arrayRate[1] = 0;
                                          }                 
                                        
                                          if(!$arrayRate[0]){
                                            $arrayRate[0] = 0;
                                          }
                                          $rate = $arrayRate[0].'.'.$arrayRate[1];
                                          $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                        ?>
                                        <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                              </div>  
                            </div>
                          </div>
                      </div>

                      <div class="width100">
                        <?php foreach ($ShoppingBizList as $key => $biz) { ?>
                          <?php if($key < 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                                <?php $businessLastImg = 'http://placehold.it/220x120'; ?>
                              <?php //foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $latestPicKey = count($biz->BusinessImages) - 1;
                                  if($latestPicKey >= 0){
                                    $businessLastImg = $biz->BusinessImages[$latestPicKey]->file_path.$biz->BusinessImages[$latestPicKey]->filename;              }
                               //} ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street: 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                        <?php
                                              
                                                $arrayRate = explode('.', $biz->average_rate);
                                                if(isset($arrayRate[1])){
                                                  if($arrayRate[1] > 5) { 
                                                    $arrayRate[0]++; $arrayRate[1] = 0; 
                                                  }
                                                  if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                                     $arrayRate[1] = 5; 
                                                  }
                                                } else {
                                                  $arrayRate[1] = 0;
                                                }
                                                $rate = $arrayRate[0].'.'.$arrayRate[1];
                                                $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                              ?>
                                              <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $rate;?> salakot rating">&nbsp;</i>
                                    </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                     
                     <div class="width100">
                        <?php foreach ($ShoppingBizList as $key => $biz) { ?>
                          <?php if($key > 3) { ?>
                          <div class="col-md-4 smallPadding">
                            <div class="item_holder">
                              <?php $businessLastImg = 'http://placehold.it/200x200'; ?>
                              <?php foreach ($biz->BusinessImages as $key => $bizImages) { 
                                  $businessLastImg = $bizImages->file_path.$bizImages->filename;
                               } ?>
                              <?php echo Phalcon\Tag::image(array($businessLastImg, 'class' => 'img-responsive img-rounded item_img')); ?>
                              <div class="item_desc">
                                <h4 class="align-center"><?php echo Phalcon\Tag::linkTo(array('business/view/'.$biz->id, '<span class=""></span>'.$biz->name, 'class' => 'text-primary')); ?></h4>
                                <p style="font-size:12px;"><i class="fa fa-home"></i>&nbsp;&nbsp;<?php echo (isset($biz->street) || ($biz->street = '') ? $biz->street : 'No Street Info'); ?></p>
                                
                                <div class="rating1" >
                                    <?php
                                      $arrayRate = explode('.', $biz->average_rate);
                                      if(isset($arrayRate[1])){
                                        if($arrayRate[1] > 5) { 
                                          $arrayRate[0]++; $arrayRate[1] = 0; 
                                        }
                                        if($arrayRate[1] < 5 && $arrayRate[1] > 0) { 
                                           $arrayRate[1] = 5; 
                                        }
                                      } else {
                                        $arrayRate[1] = 0;
                                      }
                                      $rate = $arrayRate[0].'.'.$arrayRate[1];
                                      $class_rate = $arrayRate[0].'_'.$arrayRate[1]; 
                                    ?>
                                    <i class="salakot-img salakot_<?php echo $class_rate;?>" data-toggle="tooltip" title="<?php echo $biz->average_rate;?> salakot rating">&nbsp;</i>
                                </div>
                              </div>
                            </div>
                          </div>
                          <?php } ?> 
                        <?php } ?> 
                      </div>
                      <span class="pull-right"><strong><a href="" style="color:red!important">See More....</a></strong></span>
                      <?php } ?>
                    </div>
                    <div class="col-md-3">
                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TOP DEALS FOR THE WEEK</strong></h4>


                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>
                        

                         

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>LATEST LIST</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>

                      <div style="background-color:#eee;min-height:300px;padding:5px;margin-bottom:10px;">
                          <h4 style="color:#cc2222"><strong>TODAY IN TALK</strong></h4>

                          <div style="background-color:#fff;">
                              
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="background-color:#fff;max-width:95%;margin-left:5px;padding:3px;margin-bottom:5px;">
                                <div class="media">
                                  <div class="media-left">
                                    <a href="#">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="...">
                                    </a>
                                  </div>
                                  <div class="media-body btn-primary">
                                    <h4 class="media-heading">Deal Name</h4>
                                    <p style="font-size:9px;">details,details,details,details,details,details,</p>
                                  </div>
                                </div>
                            </div>

                          </div>

                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>
            

           
