<?php echo $this->tag->stylesheetLink("themes/mybarangay1/css/select2.min.css"); ?>
<?php echo $this->tag->javascriptInclude("themes/mybarangay1/js/select2.min.js"); ?>
<div class="container containerBorder" id="container">
	<div class="col-md-12 bg-white">
		<div class="row">
			
			<div class="col-md-12 bg-primary container" style="margin-bottom:25px;">
				<h1>Add a Business</h1>
				<p>Please note: This business page will not appear in search results until it has been approved by our moderators.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 ">
				<?php $this->partial("layouts/elements/profile_widget"); ?>	
			</div>
			<div class="col-md-6" style="margin-top:10px;border:1px solid #efefef;">
				<?php echo Phalcon\Tag::form(array("review/new_business", "method" => "post")); ?>
				  	<div class="col-md-12">
						<div class="form-group">
							<label>Business Name</label>
							<input name="name" type="text" class="form-control" placeholder="Clear Trust">
						</div>
						<div class="form-group">
							<label>Website Address</label>
							<input name="website" type="text" class="form-control" placeholder="http://cleartrust.ca">
						</div>
						<div class="form-group">
							<label>Telephone</label>
							<input name="telephone" type="text" class="form-control" placeholder="(222) 222-2222">
						</div>
						<div class="form-group">
							<label>Address</label>
							<input name="street" type="text" class="form-control" placeholder="123 anywhere street">
						</div>
						<div class="form-group">
							<label>City</label>
							<input name="city" type="text" class="form-control"  placeholder="City">
						</div>
						
						<div class="form-group">
							<label>Country</label>
							<select name="country_id"  type="select" class="form-control">
									<option value="">Select country</option>
								<?php foreach ($countries as $key => $country) { ?>
									<option value="<?php echo $country->id; ?>"><?php echo $country->country; ?></option>
								<?php } ?>
							</select>
						</div>
						<div class="form-group">
							<label>Category</label>
							<small>Select up to 3 categories. The more specific the better.</small>
							<div id="selectedCategories">
							</div>
							<input type="hidden" name="business_category_ids" id="businessCategoryIds">
							<select name="business_category_id"  type="select" class="form-control js-data-example-ajax" id="businessCategories" placeholder="Select categories">
								<!-- <?php //foreach ($businessCategories as $key => $businessCategory) { ?>
									<option value="<?php //echo $businessCategory->id; ?>"><?php //echo $businessCategory->name; ?></option>
								<?php //} ?> -->
							</select>
						</div>
						<!-- <div class="form-group">
							<label>Sub-category</label>
							<select name="business_sub_category_id"  type="select" class="form-control" id="businessSubCategories">
									<option value="">Select sub-category</option>
								
							</select>
						</div>
						<div class="form-group">
							<label>Sub-category A </label>
							<select name="business_asub_category_id"  type="select" class="form-control" id="businessSubCategoriesA">
									<option value="">Select sub-category a</option>
								
							</select>
						</div> -->
						<div class="form-group">
							<div class="checkbox">
					          <label>
					            <input type="checkbox" name="opened"> This business recently opened or is opening soon
					          </label>
					        </div>
						</div>
						<div class="form-group">
							<div class="checkbox">
					          <label>
					            <input type="checkbox" id="checkToReview" checked> Write a review for this business
					          </label>
					        </div>
						</div>
						<div class="" id="reviewBox">
							<!-- <div class="form-group">
								<span class="fa fa-star btn btn-success btn-xs rate" data-rate="1"></span>&nbsp;<span class="fa fa-star btn btn-success btn-xs rate" data-rate="2"></span>&nbsp;<span class="fa fa-star btn btn-danger btn-xs rate" data-rate="3"></span>&nbsp;<span class="fa fa-star btn btn-danger btn-xs rate" data-rate="4"></span>&nbsp;<span class="fa fa-star btn btn-warning btn-xs rate" data-rate="5"></span>
								<input name="rate" type="text" class="hidden" id="rate">
							</div>
							 -->
							 <div class="stars">
								<input type="radio" name="rate" class="star-1" id="star-1" />
								<label class="star-1" for="star-1">1</label>
								<input type="radio" name="rate" class="star-2" id="star-2" />
								<label class="star-2" for="star-2">2</label>
								<input type="radio" name="rate" class="star-3" id="star-3" />
								<label class="star-3" for="star-3">3</label>
								<input type="radio" name="rate" class="star-4" id="star-4" />
								<label class="star-4" for="star-4">4</label>
								<input type="radio" name="rate" class="star-5" id="star-5" />
								<label class="star-5" for="star-5">5</label>
								<span></span>
							</div>
							<div class="form-group">
								<label> Write a review for this business</label>
								<textarea name="review" type="textarea" class="form-control" placeHolder="Start your review..."></textarea> 
							</div>
						</div>

						<div class="form-group">
						  <div class="text-center">
							<button type="submit" class="btn btn-primary width100">Add Business</button>
						  </div>
						</div>
						<br/>

				  	</div>
				<?php echo Phalcon\Tag::endForm(); ?>
				<br>
			</div>
			<div class="col-md-3 text-center">
				<h1 class="text-danger"><strong>Negosyo</strong></h1>
				<h3>Get your business listed in <span class="text-primary"><strong>MyBarangay</strong></span>.</h3>
				<div class="col-md-10 col-md-offset-1">
				<?php echo Phalcon\Tag::image(array("themes/mybarangay1/img/biz/new_biz.jpg", 'class' => 'img-responsive img-rounded img-block')); ?>
				</div>
			</div>
		</div>
		<br><br>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {

		$('[data-toggle="tooltip"]').tooltip();

		$('.rate').on('click', function(){
			var rate = $(this).data('rate');
			$('#rate').val(rate);
		});
		$('#checkToReview').on('click', function(){
			$('#reviewBox').toggleClass('hidden');
		});

		$('#businessCategories').on('change', function(){
			var id = $(this).attr('id');
			var div = $('div.category_item #'+id);
			
			if(div.length){
				div.remove();
				$('#businessCategories option[value=' + id + ']').remove();
			}
			if($('#businessCategories option').length < 4) {
				$('#selectedCategories').html($(this).text());
				var values = $.map($('#businessCategories option'), function(e) { return e.value; });
				values.join(',');
				$('#businessCategoryIds').val(values);
			} else {
				alert('3 categories only');
			}
		});

		$(document).on('click', '.remove', function(){
			var div = $(this).closest('div.category_item');
			var id = div.attr('id');
			div.remove();
			$('#businessCategories option[value=' + id + ']').remove();
			var values = $.map($('#businessCategories option'), function(e) { return e.value; });
			values.join(',');
			$('#businessCategoryIds').val(values);
		});

		function formatRepo (category) {
			var markup = '';
		    if (category.loading) return category.text;

		    markup = 
		    '<div class="category_item" id="'+category.id+'">' + category.main_title + ' <i class="fa fa-caret-right"></i> ' + category.title + ' <i class="fa fa-caret-right"></i> ' + category.sub_title +'</div>';
		    category.text = '<div class="category_item" id="'+category.id+'"><small class="text-danger remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times btn btn-xs"></i></small> <small class="text-info">' + category.main_title + ' <i class="fa fa-caret-right"></i> ' + category.title + ' <i class="fa fa-caret-right"></i> ' + category.sub_title +'</small></div>' ;

		    if (!category.sub_title) {
		    	markup = 
			    '<div class="category_item" id="'+category.id+'">' + category.main_title + ' <i class="fa fa-caret-right"></i> ' + category.title + '</div>' ;
			    category.text = '<div class="category_item" id="'+category.id+'"><small class="text-danger remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times btn btn-xs"></i></small> <small class="text-info">' + category.main_title + ' <i class="fa fa-caret-right"></i> ' + category.title + '</small></div>' ;
		    }
		    
		    return markup;
		  }

		  function formatRepoSelection (category) {
			return '';
		  }


		$(".js-data-example-ajax").select2({
		  ajax: {
		    url: "/mybarangay/business_category/list",
		    dataType: 'json',
		    delay: 250,
		    data: function (params) {
		      return {
		        q: params.term, // search term
		        page: params.page
		      };
		    },
		    processResults: function (data, page) {
		      // parse the results into the format expected by Select2.
		      // since we are using custom formatting functions we do not need to
		      // alter the remote JSON data
		      return {
		        results: data.items
		      };
		    },
		    cache: true
		  },
		  escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
		  minimumInputLength: 3,
		  templateResult: formatRepo, // omitted for brevity, see the source of this page
		  templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
		});

		// $('#businessCategories').on('change', function(){ 
		// 	var bCategoryId = $(this).val();
		// 	$.getJSON("/mybarangay/business_sub_category/list/"+bCategoryId, function(data) {
		// 	    $("#businessSubCategories option").remove();
		// 	    $("#businessSubCategories").append('<option value=""> Select sub-category</option>');
		// 	    $.each(data, function(){
		// 	        $("#businessSubCategories").append('<option value="'+ this.id +'">'+ this.name +'</option>')
		// 	    });
		// 	});
		// });

		// $('#businessCategories').on('change', function(){ 
		// 	var bCategoryId = $(this).val();
		// 	$.getJSON("/mybarangay/business_sub_category/list/"+bCategoryId, function(data) {
		// 	    $("#businessSubCategories option").remove();
		// 	    $("#businessSubCategories").append('<option value=""> Select sub-category</option>');
		// 	    $.each(data, function(){
		// 	        $("#businessSubCategories").append('<option value="'+ this.id +'">'+ this.name +'</option>')
		// 	    });
		// 	});
		// });

		// $('#businessSubCategories').on('change', function(){ 
		// 	var bSubCategoryId = $(this).val();
		// 	$.getJSON("/mybarangay/business_asub_category/list/"+bSubCategoryId, function(data) {
		// 	    $("#businessSubCategoriesA option").remove();
		// 	    $("#businessSubCategoriesA").append('<option value=""> Select sub-category</option>');
		// 	    $.each(data, function(){
		// 	        $("#businessSubCategoriesA").append('<option value="'+ this.id +'">'+ this.name +'</option>')
		// 	    });
		// 	});
		// });
		
	});
</script>

