<?php echo $this->tag->javascriptInclude("themes/mybarangay1/js/ckeditor/ckeditor.js"); ?>

<div class="container containerBorder" id="container">
	<div class="col-md-12 bg-white">
		<div class="row">
			<br>
			<div class="col-md-12 bg-primary">
				<h1>Add an Item</h1>
				<p>Please note: This item will not appear in search results until it has been approved by our moderators.</p>
			</div>
		</div>
		<div class="row">
			<br>
			<div class="col-md-3 profile-widget">
				<?php $this->partial("layouts/elements/profile_widget") ?>
			</div>
			<?php echo Phalcon\Tag::form(array("thing/new", "method" => "post", "id" => "thingNew")); ?>
			<div class="col-md-6">
			  	<div class="col-md-12">
					<div class="form-group">
						<label>Item Name</label>
						<input name="name" type="text" class="form-control" >
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Details</label>
						<textarea name="details" type="textarea" class="ckeditor form-control" ></textarea> 
					</div>
				</div>
					<div class="form-group">
					  <div class="col-lg-12 text-center">
						<button type="submit" class="btn btn-primary">Add Item</button>
					  </div>
					</div>
				
				<br>
			</div>
			<div class="col-md-3 containerBorder">
				<div class="col-md-12">
					<div class="form-group">
						<label>Price</label>
						<input name="price" type="text" class="form-control" >
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Condition</label>
						<select name="thing_condition_id"  type="select" class="form-control">
								<option value="">Select condition</option>
							<?php foreach ($thingConditions as $key => $thingCondition) { ?>
								<option value="<?php echo $thingCondition->id; ?>"><?php echo $thingCondition->name; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<label>Category</label>
						<select name="thing_category_id"  type="select" class="form-control" id="thingCategory">
								<option value="">Select category</option>
							<?php foreach ($thingCategories as $key => $thingCategory) { ?>
								<option value="<?php echo $thingCategory->id; ?>" class="category category_<?php echo $thingCategory->id; ?>"><?php echo $thingCategory->name; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>
			</div>
			<?php echo Phalcon\Tag::endForm(); ?>
		</div>
		<br><br>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {

		$('#realtyType').on('change', function(){ 
			var categoryId = $(this).val();
			$.getJSON("/mybarangay/realty_categories/list/"+categoryId, function(data) {
			    $("#realtyCategory option").remove();
			    $("#realtyCategory").append('<option value=""> Select sub-category</option>');
			    $.each(data, function(){
			        $("#realtyCategory").append('<option value="'+ this.id +'">'+ this.name +'</option>')
			    });
			});
		});
		
	});
</script>

