<div class=""><!-- profile column -->
    <div class="">
              <div class="row" style="margin: 0 15px 5px 5px;">
                <div>
                  <div class="grid">
                    <figure class="effect-lexi img_link" data-id="<?php echo $userSession['id']; ?>">
                      <?php
                      // $profilePic = MemberPhotos::findFirst(array('member_id="'.$userSession['id'].'"', 'primary_pic="Yes"'));
                      // if(!isset($profilePic) && empty($profilePic)) {
                      //   $profilePix = 'http://placehold.it/250x250&text=NO+PROFILE+PIC';
                      // } else {
                      // 	$profilePix = $profilePic->file_path.$profilePic->filename;
                      // }
                      $profilePic = 'http://placehold.it/250x250&text=NO+PROFILE+PIC';
                      if(isset($userSession['primary_pic']) && !empty($userSession['primary_pic'])) {
                        $profilePic = $userSession['primary_pic'];
                      }
                      ?>
                        <?php //echo Phalcon\Tag::linkTo(array('biz/photos/'.$userSession['id'],'id' => 'img_l', Phalcon\Tag::image(array($profilePix, 'class' => 'img-responsive img-thumbnail')))); ?>
                       <?php echo Phalcon\Tag::linkTo(array('member/photos/'.$userSession['id'],'id' => 'img_l', Phalcon\Tag::image(array($userSession['primary_pic'], 'class' => 'img-responsive img-thumbnail')))); ?>
                      <figcaption>
                        <p><?php echo Phalcon\Tag::linkTo(array('biz/add_photo/'.$userSession['id'], '<i class="fa fa-camera-retro fa-2" style="color: #fff;font-size:25px;"></i>')); ?></p>
                      </figcaption>     
                    </figure>
                  </div>
                 <?php //echo Phalcon\Tag::image(array($profilePic, 'class' => 'img-responsive img-thumbnail')); ?>
                </div>
              </div>
              <div class="row" style="margin-top:20px;">
                  <div class="col-md-4">
                    <img src="http://placehold.it/60x60" alt="..." class="img-thumbnail"  style="margin-left:20px;">    
                  </div>
                  <div class="col-md-4">
                    <img src="http://placehold.it/60x60" alt="..." class="img img-thumbnail">    
                  </div>
                  <div class="col-md-4">
                    <img src="http://placehold.it/60x60" alt="..." class="img-thumbnail" style="margin-left:-20px;">    
                  </div>
              </div>
              <div class="row">
                  <div class="col-md-12 text-center">
                    
                    <h3><?php echo Phalcon\Tag::linkTo('biz/page/'.$userSession['id'] .'/'.$userSession['first_name'] .'+'.$userSession['last_name'] , strtoupper($userSession['first_name'] .' '.substr($userSession['last_name'], 0, 1).'.' )); ?> <?php echo Phalcon\Tag::linkTo(array('biz/update/'.$userSession['id'].'/'.$userSession['first_name'].'+'.$userSession['last_name'], '<span class="fa fa-pencil"></span>', 'class' => 'pull-right', 'data-toggle' => 'tooltip', 'title' => 'Update profile')); ?></h3>
                </div>
              </div>
              <br/>
              <div class="row">
                <div style="margin-left:15px;width:89%;position:relative;border:1px solid #ccc;border-radius:10px;padding:10px; float:left;">
                  <p>Business Description Here...</p>
                </div>
              </div>

            </div>

            <div style="height:300px;border:1px solid #efefef;margin:10px;background-color:#ccc">
              <span class="danger text-center">
                <h2>Container</h2>
              </span>
            </div>
          </div><!-- profile column -->

		
	
<script type="text/javascript">
    
    $(document).ready(function(){

      $('.img_link').on('click',function(){

        $('#img_l')[0].click();

      });

    });
	$("a.clickMe").click(function() {
    console.log ( 'clicked!' );
		$(this).toggleClass("fa-chevron-down fa-chevron-right");
	});


</script>