<div class="container">
<div class="col-md-12">
<div class="panel panel-default">
<div class="panel-body">
  <div class="col-md-6 col-md-offset-3">
  <h2 class="text-primary text-center">MyBarangay for Advertiser</h2>
  </div>
  <div class="col-md-4 col-md-offset-4">
  <h3 class="text-danger">Sign in</h3>
	 <?php echo Phalcon\Tag::form(array("advertiser/login", "method" => "post", "id" => "signUpForm")); ?>
      <fieldset>
        <div class="form-group">
          <input name="email" type="email" class="form-control" id="inputEmail" placeholder="Email">
        </div>
        <div class="form-group">
          <input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password">
        </div>

        <div class="form-group">
          <div class="col-lg-12 text-center">
          <button type="button" class="btn btn-danger">Cancel</button>
          <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</div>
</div>
</div>
</div>