<div class="container bg-white ">

<!-- <h1 class="text-center">Dashboard</h1> -->

	<div class="col-md-3 profile-widget">
		<?php $this->partial("layouts/elements/profile_widget") ?>
	</div>

	<div class="col-md-9">
		<div class="panel ">
			<div class="panel-heading">
				<h3 class="panel-title">PROFILE <?php echo Phalcon\Tag::linkTo(array('member/update_profile/'.$member->id.'/'.$member->first_name.'+'.$member->last_name, '<span class="fa fa-pencil"></span>', 'class' => 'btn btn-danger btn-round btn-xs pull-right')); ?></h3>
				
			</div>
			<div class="panel-body">
				<table class="table table-striped table-hover ">
					<tbody>
						<tr>
							<td style="width:20%"><strong>Name </strong></td><td>: <?php echo $member->first_name.' '.$member->last_name; ?></td>
						</tr>
						<tr>
							<td><strong>Address </strong></td><td>: <?php echo $member->street.', '.$member->city.', '.$member->Countries->country; ?></td>
						</tr>
						<tr>
							<td><strong>Email </strong></td><td>: <?php echo $member->email; ?></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

</div>


