<br><br>
<div class="row">
	<div class="col-md-6 col-md-offset-3"><?php $this->flash->output(); ?></div>
</div>
<div class="col-md-3 col-lg-offset-4">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h4 class="head-title">Change password</h4>
		</div>
		<div class="panel-body">
			<?php  echo Phalcon\Tag::form(array($referer, 'method' => 'post', 'id' =>'resetPasswordForm')); ?>
			  <fieldset>
				<div class="form-group">
					<input name="new_password" type="password" class="form-control" id="inputEmail" placeholder="New password">
				</div>
				<div class="form-group">
					<input name="confirm_password" type="password" class="form-control" id="inputConfirmEmail" placeholder="Confirm password">
				</div>					
				<div class="form-group">
				  <div class="col-lg-12 text-center">
					<button type="button" class="btn btn-info cancel">Cancel</button>
					<button type="submit" class="btn btn-primary">Submit</button>
				  </div>
				</div>
			  </fieldset>
			<?php  echo Phalcon\Tag::endForm(); ?>
		</div>
	</div>
</div>